Finer grain reference tests
apple/swift-openapi-generator pull request #103
Opened 2023-07-07 13:10 UTC by simonjbeaumont

This PR is draft to get some feedback on the approach before fleshing it out further.

### Motivation

We have a reference test, which we've been making use of to validate end-to-end generation from OpenAPI document matches handwritten Swift files. This started out life as the canonical Petstore example from the OpenAPI specification but has since been augmented in various ways to test out some edge cases. This approach isn't scaling too well as we have an all-or-nothing test.

We also don't have great test coverage over the translation phase of the generator pipeline, which translates between the parsed OpenAPI document to an intermediate representation.

### Modifications

Add test harnesses for finer grain reference tests that exercise smaller sections of the translation phase. It should allow us to test a small OpenAPI document renders to _equivalent_ Swift source (stripping comments and reformatting).

### Result

Hopefully a more modular and maintainable testing strategy as we try to support more of the OpenAPI specification.

### Test Plan

This PR _is_ tests.

2023-07-07 22:15 UTC, czechboy0 approved these changes
Looks great, just one enhancement idea.

2023-07-07 22:15 UTC, czechboy0 commented on Tests/OpenAPIGeneratorReferenceTests/SnippetBasedReferenceTests.swift
> +            paths: {}
Overall looks great, just one idea - to avoid having to duplicate the openapi version, info, and paths keys in every snippet, could we have them be added by default, unless specified explicitly? That way you can only specify the important part of the OpenAPI doc in each test, without duplicating the unimportant parts.

Might require using Yams to parse, fill in defaults, then serialize again, but could be worthwhile.

2023-07-07 23:15 UTC, simonjbeaumont commented on Tests/OpenAPIGeneratorReferenceTests/SnippetBasedReferenceTests.swift
> +            paths: {}
I added a followup commit with one way of doing this: https://github.com/apple/swift-openapi-generator/pull/103/commits/3f377462743080ff376247a15d516d375ff8b22a.

It creates the translator from a YAML for the components only (cf. the whole OpenAPI doc).

I'm on the fence about it. There was something quite nice about knowing we used a proper (albeit) minimal OpenAPI document for each test case—even if that did mean some duplication.

2023-07-11 09:02 UTC, czechboy0 commented on Tests/OpenAPIGeneratorReferenceTests/SnippetBasedReferenceTests.swift
> +            paths: {}
I think good helper function naming can still convey that under the hood, we're producing a full OpenAPI doc, I just prefer to remove the duplicated/unchanging values, to make the tests easier to read, as you know that if it's specified in the test, it's meaningful to the object code being tested. When there's a ton of duplication, it's really hard to know what is being tested and what's just "context" bringup.

2023-07-11 09:03 UTC, czechboy0 commented on Tests/OpenAPIGeneratorReferenceTests/SnippetBasedReferenceTests.swift
> +        try self.assertHeadersTranslation(
Yeah these three methods are a great way to test this, IMO. I'd be in favor of fleshing this out. 👍

2023-07-12 15:40 UTC, czechboy0 requested changes
Just a question about the whitespace, otherwise lgtm!

2023-07-12 15:40 UTC, czechboy0 commented on Tests/OpenAPIGeneratorReferenceTests/SnippetBasedReferenceTests.swift
> +                public typealias MyString = Swift.String
I see here we have 4 spaces and 2 in the previous test, is that intentional?

2023-07-13 07:39 UTC, simonjbeaumont commented on Tests/OpenAPIGeneratorReferenceTests/SnippetBasedReferenceTests.swift
> +final class SnippetBasedReferenceTests: XCTestCase {
Might be worth it, in time. I don't think that's right now though. I could easily see this test suite covering all the "types" use cases, for example, without being too problematic.

2023-07-13 07:41 UTC, simonjbeaumont commented on Tests/OpenAPIGeneratorReferenceTests/SnippetBasedReferenceTests.swift
> +                public typealias MyString = Swift.String
Most of them use 4 spaces for the Swift code. It doesn't really matter what they use because we're not testing for that in the helper function. These are fuzzy tests w.r.t. to formatting to make them a little more robust.

2023-07-13 21:30 UTC, czechboy0 approved these changes
:shipit:

2023-07-14 13:43 UTC, merged