Add dry run option to CLI
apple/swift-openapi-generator pull request #123
Opened 2023-07-17 13:05 UTC by denil-ct

### Motivation

Resolves https://github.com/apple/swift-openapi-generator/issues/27

### Modifications

Add a dry run option to CLI `is-dry-run`

### Result

If passed, the changes would be printed to terminal, without actually affecting the file system.

<img width="508" alt="image" src="https://github.com/apple/swift-openapi-generator/assets/95201442/a7c82b20-b02c-491c-8682-71053fca5200">

### Test Plan

TBD

2023-07-17 13:15 UTC, czechboy0 commented on Sources/swift-openapi-generator/runGenerator.swift
> -        print("File \(outputFilePath.lastPathComponent): \(didChange ? "changed" : "unchanged")")
We can continue printing this line, it'd be useful to still see if the contents of this file changed or not, even in dry run.

2023-07-17 14:04 UTC, denil-ct commented on Sources/swift-openapi-generator/runGenerator.swift
> -        print("File \(outputFilePath.lastPathComponent): \(didChange ? "changed" : "unchanged")")
Moved it to `replaceFileContents` method to avoid duplication.

2023-07-17 14:32 UTC, czechboy0 requested changes
Two more minor requests, thanks.

2023-07-17 14:32 UTC, czechboy0 commented on Sources/swift-openapi-generator/runGenerator.swift
> +        }
I don't think we need it, as it's already included in the launch summary that it's dry run.

2023-07-17 14:32 UTC, czechboy0 commented on Sources/swift-openapi-generator/runGenerator.swift
> +            }
This method shouldn't print anything, just return whether the file contents have changed. Let's keep the printing in the caller, though.

2023-07-17 14:36 UTC, denil-ct commented on Sources/swift-openapi-generator/runGenerator.swift
> +            }
I thought about it, but then I couldn't differentiate if the file exists or not. Should I drop that operation or return a tuple or a state instead of a singular bool?

2023-07-17 21:38 UTC, czechboy0 commented on Sources/swift-openapi-generator/runGenerator.swift
> +            }
Sure, expanding the return value makes sense.

2023-07-18 23:46 UTC, czechboy0 approved these changes
Looks good, thanks!

2023-07-19 09:27 UTC, simonjbeaumont requested changes

2023-07-19 09:27 UTC, simonjbeaumont commented on Sources/swift-openapi-generator/runGenerator.swift
> +            }
I think that we've added a bunch of unnecessary complexity between these two functions.

I think that's because we said that this function shouldn't print. I don't agree. IMO a function that can operate in dry run mode should either:
- Do what it was asked (doesn't need to print); or
- Print what it would have done.

If we allowed this function to print the rest of the stack would be unaffected.

2023-07-19 09:58 UTC, czechboy0 commented on Sources/swift-openapi-generator/runGenerator.swift
> +        }
I think we can get rid of this print, the summary below is enough to know what the generator did for this file.

2023-07-19 10:02 UTC, denil-ct commented on Sources/swift-openapi-generator/runGenerator.swift
> +        }
Just overwritten does not convey the full meaning imo. It doesn't distinguish between the file existing or not.

2023-07-19 10:03 UTC, simonjbeaumont commented on Sources/swift-openapi-generator/runGenerator.swift
> +            }
Yes. Side-effects should be replaced with prints. Rather than hypothetical-side-effects being passed back up through the stack for no other reason and the caller needing to keep track of when how to print them.

2023-07-19 10:08 UTC, denil-ct commented on Sources/swift-openapi-generator/runGenerator.swift
> +            }
In that case, can we remove the return value entirely?

2023-07-19 10:08 UTC, czechboy0 commented on Sources/swift-openapi-generator/runGenerator.swift
> +        }
Is that important though, whether the file existed before or not? What would it help you achieve?

2023-07-19 10:10 UTC, denil-ct commented on Sources/swift-openapi-generator/runGenerator.swift
> +        }
I thought from the point of filesystem operations. To the end user its not much relevant.
Will drop it then.

2023-07-19 11:19 UTC, simonjbeaumont commented on Sources/swift-openapi-generator/runGenerator.swift
> +            }
IMO, yes.

2023-07-20 08:33 UTC, simonjbeaumont approved these changes

2023-07-20 08:33 UTC, simonjbeaumont commented on Sources/swift-openapi-generator/runGenerator.swift
>      }
At this stage, I'm going to approve the PR because it does what it set out to do.

However, IMO the code has become a bit too branchy. On inspection, I don't think that's really because of this PR.


We could also make use of some `guards` to early-return and make the code more linear.

Finally, this function also only replaces the contents if they are different but isn't clear from its name. This is an important nuance because IIUC this affects the timestamp on the file and, therefore, the rest of the build graph.

This function could therefore be rewritten as:

```swift
    static func replaceFileContentsIfDifferent(
        at path: URL,
        with data: Data,
        isDryRun: Bool
    ) throws {
        if let existingData = try? Data(contentsOf: path), existingData == data {
            print("File \(path.lastPathComponent) already up to date.")
            return
        }
        guard !isDryRun else {
            print("Not writing file \(path.lastPathComponent) (dry run).")
            return
        }
        print("Writing file \(path.lastPathComponent).")
        try data.write(to: path)
    }
```

At this point it is questionable why we had this `@discardableResult` function that took a throwing closure anyway, because at the call site it's basically the only thing that's called by `runGenerator(...)`.

All that said, I'm hitting approve here because removing this complexity isn't on your plate @denil-ct :)

2023-07-20 09:08 UTC, denil-ct commented on Sources/swift-openapi-generator/runGenerator.swift
>      }
I'll be happy to simplify it another PR post this.

2023-07-20 12:58 UTC, czechboy0 requested changes
One last request, otherwise lgtm.

2023-07-20 12:58 UTC, czechboy0 commented on Sources/swift-openapi-generator/GenerateCommand.swift
> +    var isDryRun: Bool = false
Oh sorry for the late request, could we just make it `--dry-run`? At the moment, the name would be `--is-dry-run`, which feels like a question rather than an instruction.

I believe there's a parameter on the Option property wrapper customize the CLI name, which means you won't need to change the property name itself.

2023-07-20 16:15 UTC, denil-ct commented on Sources/swift-openapi-generator/GenerateCommand.swift
> +    var isDryRun: Bool = false
I agree, although I just followed the same style as `isPluginInvocation`

2023-07-20 18:09 UTC, czechboy0 commented on Sources/swift-openapi-generator/GenerateCommand.swift
> +    var isDryRun: Bool = false
Good point, but fortunately that one is getting renamed in #98.

2023-07-21 17:36 UTC, czechboy0 commented
@denil-ct Unfortunately #98 touched similar code as your PR, so there are a few conflicts you'll need to resolve before landing. Once that's all green, and https://github.com/apple/swift-openapi-generator/pull/123#discussion_r1269421605 is addressed, we can land it.

2023-07-22 14:11 UTC, czechboy0 approved these changes

2023-07-22 14:15 UTC, merged