Enable the generated server-side code to validate the content-type.
apple/swift-openapi-generator pull request #140
Opened 2023-07-25 13:07 UTC by takeshi-1000

### Motivation
I am interested this tool and have selected something that I can work on.
Resolve #16 

### Modifications

To validate content-type header string in server program, I modify `traslateServerDesirializer` method . 

### Result

For example you will define below opeapi yaml 

```
  /greet:
    post:
      operationId: postGreeting
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
```

when you try the request, runtime error happen.

```
$ curl localhost:8080/api/greet3 -X POST \             
> -H "Content-Type: application/json" \
> -d '{ "name": "foo" }'

{"error":true,"reason":"Server error - operationID: postGreeting, request: path: \/api\/greet, query: <nil>, method: HTTPMethod(value: OpenAPIRuntime.HTTPMethod.(unknown context at $106e9fd78).OpenAPIHTTPMethod.POST), header fields: [Host: localhost:8080, User-Agent: curl\/7.88.1, Accept: *\/*, Content-Type: application\/json, Content-Length: 64], body (prefix): { \"name\": \"foo\"}, metadata: path parameters: [:], query parameters: [], operationInput: <nil>, operationOutput: <nil>, underlying error: Unexpected Content-Type header: application\/json"}
```

### Test Plan

I have made the necessary changes to adapt to the newly generated code on the reference server side and have confirmed that it passes the tests locally.

2023-07-25 13:59 UTC, czechboy0 requested changes
Hi @takeshi-1000, thanks for taking this up!

Overall, your change looks good, can you just add a unit test? For example, you could create a variant of the test for `createPet` ([here](https://github.com/apple/swift-openapi-generator/blob/22a7d7af0be75447625e091d5ddf73bdd192c96d/Tests/PetstoreConsumerTests/Test_Server.swift#L129)) that purposefully passes the incorrect content type and verifies that an error was thrown with `XCTAssertThrowsError` (but no need to test the contents of the error, as it's an internal type).

2023-07-25 23:54 UTC, takeshi-1000 commented
@czechboy0 
Thank you for reviewing . 
I tried to add, but `XCTAssertThrowsError` seems not to supported async method. 
https://developer.apple.com/documentation/xctest/1500795-xctassertthrowserror

![2023-07-26 8 48のイメージ](https://github.com/apple/swift-openapi-generator/assets/16571394/83bed196-c68e-4378-9357-f5f2ce8847c1)

I am considering the following code, but is there any better alternative?

```
 client = .init(
            createPetBlock: { input in
                return .created(
                    .init(
                        headers: .init(
                            X_Extra_Arguments: .init(code: 1)
                        ),
                        body: .json(
                            .init(id: 1, name: "Fluffz")
                        )
                    )
                )
            }
        )
        
        do {
            _ = try await server.createPet(
                .init(
                    path: "/api/pets",
                    method: .post,
                    headerFields: [
                        .init(name: "x-extra-arguments", value: #"{"code":1}"#),
                        .init(name: "content-type", value: "text/plain; charset=utf-8"),
                    ],
                    encodedBody: #"""
                        {
                          "name" : "Fluffz"
                        }
                        """#
                ),
                .init()
            )
            XCTFail("The method should have thrown an error.")
        } catch {
            XCTAssertNotNil(error)
        }
```

2023-07-26 05:28 UTC, czechboy0 commented
Ah you're right. Yeah, a manual do/catch block, where you XCTFail at the end of the do block, and do nothing in the catch block is how I've worked around this limitation.

2023-07-26 11:51 UTC, czechboy0 requested changes
Two more suggestions, just to simplify the tests a bit more, otherwise looks good. 👍

2023-07-26 11:51 UTC, czechboy0 commented on Tests/PetstoreConsumerTests/Test_Server.swift
> +        }
```suggestion
        } catch {}
```

You can remove the non-nil check, as the `error` variable in the `catch` block is of type `Error`, not `Error?`.

2023-07-26 11:51 UTC, czechboy0 commented on Tests/PetstoreConsumerTests/Test_Server.swift
> +                )
```suggestion
                XCTFail("The handler should not have been called")
```

2023-07-26 13:43 UTC, takeshi-1000 commented
Thank you for checking ! I applied your suggestion  .

2023-07-26 13:56 UTC, czechboy0 approved these changes
Looks great, thank you!

2023-07-26 13:56 UTC, czechboy0 commented
@swift-server-bot add to allowlist

2023-07-26 18:29 UTC, czechboy0 requested changes

2023-07-26 18:29 UTC, czechboy0 commented on Tests/PetstoreConsumerTests/Test_Server.swift
> +                XCTFail("The handler should not have been called")
The CI is complaining about this, we need to return Never here, for example like this.
```suggestion
                XCTFail("The handler should not have been called")

                fatalError("Unreachable")
```

2023-07-26 20:01 UTC, takeshi-1000 commented on Tests/PetstoreConsumerTests/Test_Server.swift
> +                XCTFail("The handler should not have been called")
Oh sorry, after applied the suggestion, test looks passed locally.

2023-07-26 20:10 UTC, takeshi-1000 commented
I missed https://github.com/apple/swift-openapi-generator/blob/main/CONTRIBUTING.md#run-scriptssoundnesssh, and am confirming .

2023-07-26 20:52 UTC, simonjbeaumont approved these changes
Thanks @takeshi-1000 for getting involved!

2023-07-26 20:58 UTC, merged