Retain operation level parameters over path level ones
apple/swift-openapi-generator pull request #183
Opened 2023-08-09 18:22 UTC by arthurcro

### Motivation

Fixes https://github.com/apple/swift-openapi-generator/issues/168.

### Modifications

Previously, an operation's parameters were returned as a concatenation of the parameters from the path item level with those at operation level.

However, this is incorrect according to https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#fixed-fields-7. 
> A list of parameters that are applicable for all the operations described under this path. These parameters can be overridden at the operation level, but cannot be removed there. The list MUST NOT include duplicated parameters.

With this change, we are merging the two arrays of parameters using a unique identifier of the location + name of parameters. If duplicate parameters exist, only the parameters from the operation level are preserved.

### Result

After this change, an operation's parameters won't contain any duplicate. 

### Test Plan

Add tests for `OperationDescription.allParameters` at `Tests/OpenAPIGeneratorCoreTests/Translator/Operations/Test_OperationDescription.swift`.

2023-08-09 20:13 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Operations/OperationDescription.swift
> +            var mergedParameters = [UnresolvedParameter]()
```suggestion
            var mergedParameters: [UnresolvedParameter] = []
```

Nit: prefer a literal.

2023-08-09 20:14 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Operations/OperationDescription.swift
> +            var uniqueIdentifiers = Set<String>()
```suggestion
            var mergedParameters: [UnresolvedParameter] = []
            var uniqueIdentifiers: Set<String> = []
```

Style nit: prefer a literal.

2023-08-09 20:15 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Operations/OperationDescription.swift
> +                let identifier = resolvedParameter.name + resolvedParameter.location.rawValue
```suggestion
                let identifier = resolvedParameter.location.rawValue + ":" + resolvedParameter.name
```

Nit: it reads better if the larger scope (location) goes first, then the name that only needs to be unique within the location, and let's separate it with a character for easier readability when debugging.

2023-08-09 20:16 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Operations/OperationDescription.swift
> +                else { continue }
```suggestion
                guard !uniqueIdentifiers.contains(identifier) else { 
                    continue 
                }
```

Style nit.

2023-08-09 20:19 UTC, czechboy0 commented
The change looks good, just a few minor style suggestions.

For testing, you can create a new unit test file `Tests/OpenAPIGeneratorCoreTests/Translator/Operations/Test_OperationDescription.swift`, follow the style seen e.g. in `Tests/OpenAPIGeneratorCoreTests/Translator/Content/Test_ContentType.swift`, and create an `OperationDescription` with duplicated params in the path and operation in the unit test and verify that `allParameters` returns just the unique ones.

2023-08-09 20:56 UTC, arthurcro commented
Thank you for the nice review, I applied all suggestions! 🙂
I'll add a test shortly and mark this as ready for review.

2023-08-10 19:20 UTC, arthurcro commented on Tests/OpenAPIGeneratorCoreTests/Translator/Operations/Test_OperationDescription.swift
> +    func testAllParameters_duplicates_retainOnlyOperationParameters() throws {
@czechboy0 I'm not sure about usign the `YamsParser` here. I could not find an easier way to construct an `OperationDescription`. It needs an `OpenAPI.Endpoint` but it does not have a `public` initializer. 
I thought about constructing a `OpenAPI.Document` or `OpenAPI.PathItem`manually but I found it make the test harder to read and understand. What do you think? 🙂

2023-08-10 20:02 UTC, czechboy0 commented on Tests/OpenAPIGeneratorCoreTests/Translator/Operations/Test_OperationDescription.swift
> +    func testAllParameters_duplicates_retainOnlyOperationParameters() throws {
I think constructing `OpenAPI.PathItem` is better than creating a document from YAML. See if you can get that to work to initialize an `OperationDescription`.

2023-08-10 20:02 UTC, czechboy0 commented on Tests/OpenAPIGeneratorCoreTests/Translator/Operations/Test_OperationDescription.swift
> +    func testAllParameters_duplicates_retainOnlyOperationParameters() throws {
From `OpenAPI.PathItem`, you can get the `OpenAPI.PathItem.Endpoint` for your tested operation.

2023-08-10 20:08 UTC, czechboy0 commented
@swift-server-bot add to allowlist

2023-08-10 20:10 UTC, arthurcro commented on Tests/OpenAPIGeneratorCoreTests/Translator/Operations/Test_OperationDescription.swift
> +    func testAllParameters_duplicates_retainOnlyOperationParameters() throws {
Alright, thanks for the feedback. I'll work on updating the tests to use that instead!

2023-08-10 20:31 UTC, arthurcro commented on Tests/OpenAPIGeneratorCoreTests/Translator/Operations/Test_OperationDescription.swift
> +    func testAllParameters_duplicates_retainOnlyOperationParameters() throws {
I've pushed the changes. Thanks to the tests I also noticed I was retaining the path parameter over the operation ones which was incorrect according to https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#path-item-object so I fixed that too!

2023-08-10 21:12 UTC, czechboy0 commented on Tests/OpenAPIGeneratorCoreTests/Translator/Operations/Test_OperationDescription.swift
> +    func testAllParameters_duplicates_retainOnlyOperationParameters() throws {
I think the order was right before, the shared path params should come before the operation specific ones.

If you flip the order back, you should be able to just slightly change your logic - do (pathParams + operationParams), get a reversed(), iterate that, then reverse the result again. I think that should get us the original order but also retain the last occurrence of any location+name pair.

2023-08-11 05:27 UTC, arthurcro commented on Tests/OpenAPIGeneratorCoreTests/Translator/Operations/Test_OperationDescription.swift
> +    func testAllParameters_duplicates_retainOnlyOperationParameters() throws {
Ah right, the order should be kept as well. I'll adjust that part, thank you!

2023-08-11 07:48 UTC, czechboy0 commented on Tests/OpenAPIGeneratorCoreTests/Translator/Operations/Test_OperationDescription.swift
> +            path: .init(["\test"]),
```suggestion
            path: .init(["/test"]),
```

2023-08-11 07:49 UTC, czechboy0 commented on Tests/OpenAPIGeneratorCoreTests/Translator/Operations/Test_OperationDescription.swift
> +    }
Can you please add one more test that verifies the correct ordering?

Could be:
- path item level: A, B
- operation level: B, C
- expected result: A, B, C

2023-08-11 07:49 UTC, czechboy0 requested changes
Just two more comments about the tests, otherwise looks great!

2023-08-11 13:06 UTC, merged