Fixes #165 - Enable documentation comment validation in swift-format
apple/swift-openapi-generator pull request #188
Opened 2023-08-10 20:03 UTC by PARAIPAN9

### Motivation

This is for better documentation
Fixes #165

### Modifications

Enabled some rules in .swift-format

### Result

The .swift-format will be changed and the rules will reflect into the project

### Test Plan

Run tests and CI

2023-08-10 20:06 UTC, czechboy0 commented
Sorry if the issue wasn't clear, part of the enablement will likely need to be to actually update all the places where the docs aren't passing validation. Otherwise our CI would go red.

2023-08-10 20:06 UTC, PARAIPAN9 commented
There is also this rule: BeginDocumentationCommentWithOneLineSummary that is comment related, currently set to false.

2023-08-10 20:06 UTC, czechboy0 commented on .swift-format
> +    "AllPublicDeclarationsHaveDocumentation" :true,
```suggestion
    "AllPublicDeclarationsHaveDocumentation" : true,
```

Nit: whitespace.

2023-08-10 20:07 UTC, czechboy0 requested changes
This will need updating the actual places missing docs (try running `./scripts/soundness` locally). That might be quite a bit of work, so if that seems like too much, feel free to put the issue back into the queue and someone else will pick it up later.

2023-08-10 20:09 UTC, czechboy0 commented
> There is also this rule: BeginDocumentationCommentWithOneLineSummary that is comment related, currently set to false.

I don't think we need to set that, it's overly strict about the abstract of each symbol. Could be added later.

2023-08-14 06:15 UTC, czechboy0 commented
Just setting the PR back to draft to communicate its status.

2023-08-14 08:07 UTC, PARAIPAN9 commented
Just a heads up to let you know that I'm still working on it, it will take a little bit of time.

2023-08-14 08:08 UTC, czechboy0 commented
No rush, @PARAIPAN9 – thanks 🙏

2023-08-22 18:56 UTC, PARAIPAN9 commented
Hello, I have another update about this PR. I've come to a stage where I need to include comment documentation for the generated files and by doing this there is reference test that is failing. What would be the best approach here? Should I modify the generator to produce the documentation, similar to how it does it for "Remark" comments?

2023-08-22 19:20 UTC, czechboy0 commented
No, let's exclude the files from being reformatted and linted. They get formatted as part of the generation process anyway, so this doesn't remove any value.

I suspect updating the script for formatting should do the trick.

2023-10-10 12:04 UTC, czechboy0 commented
@PARAIPAN9 Once you'd like this reviewed, please move the PR into Ready for review.

2023-10-10 15:29 UTC, czechboy0 requested changes
Just one question about the script, otherwise looks great, thank you!

2023-10-10 15:29 UTC, czechboy0 commented on scripts/run-swift-format.sh
> +  "${REPO_ROOT}/Sources" \
What was the issue with before? I think this would disable linting the Test and other directories, which I don't think we want. cc @simonjbeaumont

2023-10-10 17:37 UTC, PARAIPAN9 commented on scripts/run-swift-format.sh
> +  "${REPO_ROOT}/Sources" \
The problem was that it was also complaining about the generated files.

2023-10-10 20:28 UTC, czechboy0 commented on scripts/run-swift-format.sh
> +  "${REPO_ROOT}/Sources" \
We should then only exclude generated files but keep all the other ones. There are examples, integration tests and unit tests that we want to cover.

2023-10-10 20:40 UTC, PARAIPAN9 commented on scripts/run-swift-format.sh
> +  "${REPO_ROOT}/Sources" \
Yes that's right, then I’ll tweak the script to exclude only the generated files.

2023-10-11 05:18 UTC, czechboy0 requested changes

2023-10-11 05:18 UTC, czechboy0 commented on scripts/run-swift-format.sh
> +  | grep -z -v 'Tests/OpenAPIGeneratorReferenceTests/Resources/ReferenceSources/Petstore' \
```suggestion
  | grep -z -v 'Tests/OpenAPIGeneratorReferenceTests/Resources' \
```

And please also exclude and remove any changes to the Sources/swift-openapi-generator/Documentation.docc. Otherwise will be ready to go.

2023-10-11 08:25 UTC, czechboy0 approved these changes
Thank you, @PARAIPAN9!

2023-10-11 08:25 UTC, merged

2023-10-11 08:25 UTC, czechboy0 commented
@PARAIPAN9 If you'd be interested, it'd be good to get this change into swift-openapi-runtime as well, but no pressure 🙂

2023-10-11 08:28 UTC, PARAIPAN9 commented
Sure, no problem!!