Emit JSON path reference in comments for all generated types
apple/swift-openapi-generator pull request #196
Opened 2023-08-15 03:47 UTC by takeshi-1000

### Motivation

Resolve #13

### Modifications

This pull request is currently incomplete.
The generated Types.swift ( `Tests/OpenAPIGeneratorReferenceTests/Resources/ReferenceSources/Petstore/Types.swift` )  in this codebase shows the comment changes we applied this time.

I would like to confirm if there are some misunderstanding, and after that I will do the rest.

- Fixed hard-coded parts
- Added test code
- Add userDescription if needed

### Result

Some comments in Types.swift is generated, like `Tests/OpenAPIGeneratorReferenceTests/Resources/ReferenceSources/Petstore/Types.swift`.

### Test Plan

TODO

2023-08-15 08:23 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Parameters/translateParameter.swift
> +                                                                    subPath: "\(parameter.location.rawValue)/\(parameter.name)")
```suggestion
        let comment: Comment? = parent.docCommentWithUserDescription(
            nil,
            subPath: "\(parameter.location.rawValue)/\(parameter.name)"
        )
```

Nit: whitespace

2023-08-15 08:24 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/RequestBody/translateRequestBody.swift
> +        typeName: TypeName,
```suggestion
```

You shouldn't need to pass this type in, it's already present on `requestBody.typeUsage.typeName`.

2023-08-15 08:27 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/RequestBody/translateRequestBody.swift
> +                .enumCase(.init(
```suggestion
                .enumCase(
```

I think we have a utility function on `Declaration` that allows passing in the parameters directly, don't we?

2023-08-15 08:27 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/RequestBody/translateRequestBody.swift
> +                                                  for: requestBody)
```suggestion
        let members = try requestBodyContentCases(
            typeName: type,
            for: requestBody
        )
```

Nit: whitespace

2023-08-15 08:28 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/RequestBody/translateRequestBody.swift
> +                                                  for: requestBody)
```suggestion
        let members = try requestBodyContentCases(for: requestBody)
```

As commented above, I don't think we need to pass it in, the type name should already be present on `requestBody`.

2023-08-15 08:32 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponseHeader.swift
> +        responseKind: String = "",
```suggestion
        responseKind: ResponseKind,
```

If the response kind is needed, pass it in as the typesafe type `ResponseKind` and don't provide a default value, we want to make sure all callers are updated.

2023-08-15 08:33 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponse.swift
> +                  : "reponses/\(responseKind)/headers"
```suggestion
                  : "responses/\(responseKind)/headers"
```

Typo

2023-08-15 08:34 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponse.swift
> +        responseKind: String = "",
```suggestion
        responseKind: ResponseKind,
```

As below, let's pass in the typesafe variant and not provide a default.

2023-08-15 08:34 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponseHeader.swift
> +            : "reponses/\(responseKind)/headers/\(header.name)"
```suggestion
            : "responses/\(responseKind)/headers/\(header.name)"
```

2023-08-15 08:34 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponseOutcome.swift
> +                responseKind: responseKind.jsonPathComponent,
```suggestion
                responseKind: responseKind,
```

2023-08-15 08:36 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/TypeAssignment/TypeName.swift
> +        description.contains("#/components")
I think you could instead check if the first two JSON components are `#` and `components`, that'd at least use the internal `components` storage and be a little more reliable.

2023-08-15 08:37 UTC, czechboy0 requested changes
This is definitely the right direction! Added a few comments, we can get this PR cleaned up and landed, and then you can continue to address any remaining missing comments in a separate PR.

2023-08-16 00:53 UTC, takeshi-1000 commented
Thanks for the quick confirmation! The fix is ​​still incomplete, but I just put in something that can be applied immediately.

2023-08-16 04:42 UTC, czechboy0 commented
@swift-server-bot add to allowlist

2023-08-16 08:05 UTC, czechboy0 commented
> Thanks for the quick confirmation! The fix is ​​still incomplete, but I just put in something that can be applied immediately.

Sure – can you please just resolve the CI failures and we could land this PR? Then you can continue to work on the missing bits in a separate PR.

2023-08-16 09:45 UTC, takeshi-1000 commented on Sources/_OpenAPIGeneratorCore/Translator/TypeAssignment/TypeName.swift
> +        description.contains("#/components")
Exactly. I fixed.
https://github.com/apple/swift-openapi-generator/pull/196/commits/4188460d7e724641a0bda1a85e42990d2a26f613#diff-9d2dcac6bf1aa7b2aee70f0b1ff4de6be4efe7e702a63f0145012a4f45a31ac9

2023-08-16 10:01 UTC, takeshi-1000 commented
@czechboy0 
I modify some code, could you check please? 
Also As you suggested, I plan to address some other issues in another PR.
(There are places where userDescription is not reflected in comments, and characters are implemented with hard code)
Is it okay to open these issues?

2023-08-16 11:11 UTC, czechboy0 requested changes
A few more stylistic nits to ensure better readability.

2023-08-16 11:11 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/RequestBody/translateRequestBody.swift
>              let identifier = contentSwiftName(content.content.contentType)
```suggestion
            let contentType = content.content.contentType
            let identifier = contentSwiftName(contentType)
```

2023-08-16 11:11 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/RequestBody/translateRequestBody.swift
> +                    .typeName
```suggestion
            let typeName = requestBody.typeUsage.typeName
            let subPath: String = {
                let contentPath = (typeName.isComponent ? "" : "requestBody/") + "content"
                return "\(contentPath)/\(contentType.lowercasedTypeAndSubtypeWithEscape)"
            }()
            let contentCase: Declaration = .commentable(
                typeName
```

2023-08-16 11:11 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponse.swift
> +        responseKind: ResponseKind?,
Actually, I wonder - don't we already have this information in `typeName`'s JSON components? Why do we need to pass `responseKind`, especially since it's optional so won't always be there?

2023-08-16 11:11 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponse.swift
> +            }
There's quite a lot of duplication of prefixes of the comments, could we make it a bit more readable by building it up gradually using some local variables, and concatenating more components as needed? Otherwise it's difficult to read how the different branches of the if/else are different.

2023-08-16 11:11 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponse.swift
> +            responseKind: nil,
Well, this is unfortunate. Now I wonder if we don't already have this info in `typeName`?

2023-08-16 11:11 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponseHeader.swift
> +        }()
If the comment is the only reason we have to start passing these other two params, let's move the creation of the comment to the caller of this method, this muddies up the purpose of the method.

2023-08-16 11:11 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/TypeAssignment/TypeName.swift
> +    var isComponent: Bool {
```suggestion
    var isInComponents: Bool {
```

2023-08-17 00:43 UTC, takeshi-1000 commented on Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponse.swift
> +            responseKind: nil,
I think so, I could not find something which access responseKind from typeName or typeResponse.

2023-08-17 00:45 UTC, takeshi-1000 commented on Sources/_OpenAPIGeneratorCore/Translator/Responses/translateResponse.swift
> +            }
I try to fix. https://github.com/apple/swift-openapi-generator/pull/196/commits/5ff67b8a1795b52ceefeae5d2c840008642e96ff

2023-08-17 08:08 UTC, czechboy0 approved these changes
Updated with one more commit, lgtm.

2023-08-17 10:10 UTC, merged

2023-08-17 10:27 UTC, takeshi-1000 commented
Thank you for suporting!