Generate all requested modes in parallel
apple/swift-openapi-generator pull request #280
Opened 2023-09-15 18:51 UTC by simonjbeaumont

### Motivation

The generator itself is synchronous, but it can be run in one of more modes: `types`, `client`, `server`, and these runs can be parallelised. This is likely to have value to most adopters since most will use at least two modes. This is especially useful for large APIs.

### Modifications

Run all the requested modes of the generator in a task group.

### Result

When running with multiple modes, generation is faster.

Concretely, when using the Github API and generating types and client, it cut the overall generation time by 40%.

### Test Plan

CI.

### Resolves

Resolves #227.

2023-09-15 19:05 UTC, czechboy0 requested changes

2023-09-15 19:05 UTC, czechboy0 commented on Sources/swift-openapi-generator/runGenerator.swift
> +                        diagnostics: diagnostics
Can you make the YAML diagnostics collector thread-safe please? I think that's the only one that could encounter problems with this change.

2023-09-15 19:07 UTC, czechboy0 commented on Sources/swift-openapi-generator/runGenerator.swift
> +                        diagnostics: diagnostics
The stderr printing one might also need a way to serialize the printing to ensure we don't get garbled output. Possibly the whole diagnostics collector protocol should become Sendable.

2023-09-18 13:26 UTC, simonjbeaumont commented on Sources/swift-openapi-generator/runGenerator.swift
> +                        diagnostics: diagnostics
I've rebased on main following merging #281 and made it all clean of warnings.

2023-09-18 13:32 UTC, czechboy0 approved these changes

2023-09-18 14:13 UTC, merged