Add url form encoder & decoder
apple/swift-openapi-generator pull request #283
Opened 2023-09-19 09:18 UTC by bfrearson

### Motivation

#195 Currently, the generated interface for request bodies that use URLEncodedForms accepts a `Data` object. This PR uses the URIEncoder/Decoder to instead provide an interface using codable types in the same way that a JSON body would.

### Modifications
Adds a new coding strategy that works with the corresponding [runtime converter updates](https://github.com/apple/swift-openapi-runtime/pull/53).

**Note:** This PR does not support encoding collections of primitives (i.e. an array of string values for a single key). This should be addressed in a future update, but it raised questions about the correct use of URIEncoder, so I didn't include it in this PR. Further discussion of the issue is in the [runtime PR](https://github.com/apple/swift-openapi-runtime/pull/53).

### Result
Generated interfaces now directly accept URLEncodedForm Codable types rather than untyped `Data`.

### Test Plan

Updated reference tests to include a request using a form body.

2023-09-21 09:53 UTC, czechboy0 commented on Tests/PetstoreConsumerTests/TestClient.swift
>      var uploadAvatarForPetBlock: UploadAvatarForPetSignature?
Please also add corresponding tests to Test_Client and Test_Server that ensures at runtime everything is correctly propagated.

2023-09-21 09:54 UTC, czechboy0 commented on Tests/OpenAPIGeneratorReferenceTests/Resources/Docs/petstore.yaml
> +  /pets/create:
Let's simplify this to only test what we want to test here - url encoded request bodies.
- remove X-Extra-Arguments from the request and response headers
- remove the 400 response
- make the success response be 204 and return no content at all

2023-09-21 09:54 UTC, czechboy0 commented on Tests/OpenAPIGeneratorReferenceTests/Resources/ReferenceSources/Petstore/Client.swift
> +                let path = try converter.renderedPath(template: "/pets", parameters: [])
Could this be due to the swift-format version mismatch again? We'll upgrade at some point, but you'll likely need to revert this to pass CI :)

2023-09-21 09:55 UTC, czechboy0 requested changes
Looks great, just a few suggestions, otherwise almost ready to go just like the runtime PR. 🙏

2023-09-24 09:52 UTC, bfrearson commented on Tests/OpenAPIGeneratorReferenceTests/Resources/ReferenceSources/Petstore/Client.swift
> +                let path = try converter.renderedPath(template: "/pets", parameters: [])
good spot thanks! Had already reverted to the correct version of swift-format, but looks like the updated version had already made these changes

2023-09-25 09:38 UTC, czechboy0 commented
@swift-server-bot add to allowlist

2023-09-25 09:38 UTC, czechboy0 approved these changes
I made a few more fixes, looks good now.

2023-09-25 09:39 UTC, czechboy0 commented
@bfrearson most notably, I had to hide the feature under the `urlEncodedForm` feature flag, as changing the generated type is an API-breaking change, so must be opt-in in 0.2.x, and will become the default in 0.3.0.

2023-09-25 09:58 UTC, merged