Fixes #276 - Unknown configuration options should throw an error
apple/swift-openapi-generator pull request #297
Opened 2023-09-25 21:57 UTC by PARAIPAN9

### Motivation

Fixes #276

### Modifications

Create a fucntion that extracts the keys from the config file and compares them with the UserConfig Coding Keys

### Result

When the config file loads, it also checks for the keys to match

### Test Plan

Loaded different config files with different configurations to see if it works.

2023-09-26 06:53 UTC, czechboy0 requested changes

2023-09-26 06:53 UTC, czechboy0 commented on Sources/swift-openapi-generator/GenerateOptions.swift
> +            let yamlKeys = extractYamlKeys(yamlString: configAsString!)
```suggestion
            let configAsString = String(decoding: data, as: UTF8.self)
            let yamlKeys = extractYamlKeys(yamlString: configAsString)
```

2023-09-26 06:53 UTC, czechboy0 commented on Sources/swift-openapi-generator/UserConfig.swift
> +    static let codingKeysRawValues = Set(CodingKeys.allCases.map({ $0.rawValue }))
Please add a comment for the symbol.

2023-09-26 06:53 UTC, czechboy0 commented on Sources/swift-openapi-generator/GenerateOptions.swift
> +        return extractedKeys
I agree we need to extract the keys somehow, but I don't think we should try to write our own YAML parser here. Can you see if you can use the lower level Yams API to do the same? https://www.jpsim.com/Yams/Classes/Parser.html

2023-09-26 08:51 UTC, PARAIPAN9 commented on Sources/swift-openapi-generator/GenerateOptions.swift
> +        return extractedKeys
@czechboy0, thank you for the comments. I wasn't sure about the YAML parsing method, which is why I opened the PR without writing tests for it. I will check the link provided by you to explore other possibilities.

2023-09-28 05:50 UTC, czechboy0 requested changes
Just one more nit, and can you add a unit test please?

2023-09-28 05:50 UTC, czechboy0 commented on Sources/swift-openapi-generator/GenerateOptions.swift
> +            print("Error parsing YAML: \(error)")
I think it's better to just let the error be thrown one level up, and there emit a ValidationError saying the config isn't valid and include the description of the error thrown by Yams. So you can remove the do/catch here.

2023-09-28 06:59 UTC, PARAIPAN9 commented on Sources/swift-openapi-generator/GenerateOptions.swift
> +            print("Error parsing YAML: \(error)")
Sure thing!!

2023-09-28 09:20 UTC, PARAIPAN9 commented on Sources/swift-openapi-generator/GenerateOptions.swift
> +            print("Error parsing YAML: \(error)")
Just a quick question, where would be a good place in the codebase, to write the unit test?

2023-09-28 09:37 UTC, czechboy0 commented on Sources/swift-openapi-generator/GenerateOptions.swift
> +            print("Error parsing YAML: \(error)")
You could move the logic close to the YAML parser in the core module, and that one has unit tests that you can add to. We don't yet have a unit test target for the CLI module.

2023-09-28 09:42 UTC, PARAIPAN9 commented on Sources/swift-openapi-generator/GenerateOptions.swift
> +            print("Error parsing YAML: \(error)")
perfect, TY!!

2023-09-28 12:14 UTC, PARAIPAN9 commented
Please feel free to comment, suggest changes if still something is not right or could be improved. I really appreciate your input!!

2023-09-28 16:28 UTC, czechboy0 approved these changes
Thanks!

2023-09-28 16:29 UTC, merged