Add support for filtering OpenAPI document
apple/swift-openapi-generator pull request #319
Opened 2023-10-03 22:20 UTC by simonjbeaumont

### Motivation

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_

### Modifications

_[Describe the modifications you've made.]_

### Result

_[After your change, what will change.]_

### Test Plan

_[Describe the steps you took, or will take, to qualify the change - such as adjusting tests and manual testing.]_

2023-10-11 08:48 UTC, czechboy0 requested changes
Looks great overall, just a few small suggestions.

2023-10-11 08:48 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Hooks/DocumentFilter.swift
> +    public var paths: [OpenAPI.Path]?
Is there extra validation in the decoder of OpenAPI.Path we want to take advantage of? Or should we just make this a String?

2023-10-11 08:48 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Hooks/DocumentFilter.swift
> +        operations: [String] = [],
Is there a distinction between an empty array and a nil array? Naively, I'd expect a nil array to mean "don't filter using this axis, aka keep everything", versus an empty array, which I'd understand as "filter out everything".

2023-10-11 08:48 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Hooks/FilteredDocument.swift
> +    public mutating func requirePath(_ path: OpenAPI.Path) throws {
Super small nit, I find the word "include" a bit clearer than "require" here. Especially if we might add "exclude" down the line.

2023-10-11 08:48 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Hooks/FilteredDocument.swift
> +            throw FilteredDocumentBuilderError.operationDoesNotExist(operationID: operationID)
Very good call, will ensure adopters don't make a typo in their operation id and then spend time debugging why their operation isn't showing up.

I wonder if we should somehow "consume" all the other filters as well, and throw an error if you're trying to include something that doesn't exist in the document? Not crucial, but would make debugging a lot easier, especially since this is all stringly programming from the config file, without any autocompletion or validation.

2023-10-11 08:48 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Hooks/FilteredDocument.swift
> +            return OpenAPI.ComponentKey(rawValue: name)!
Can we throw an error if it fails to init? Looking at the impl, there might be situations where the user's document could cause this to crash, which becomes difficult to debug.

2023-10-11 08:48 UTC, czechboy0 commented on Sources/swift-openapi-generator/FilterCommand.swift
> +struct _FilterCommand: AsyncParsableCommand {
This will be useful for debugging. Could you also add a few words about it to the Configuring docc article, both about the new keys in the config file, and about using the new filter command?

2023-10-11 08:48 UTC, czechboy0 commented on Tests/OpenAPIGeneratorCoreTests/Hooks/FilteredDocumentTests.swift
> +private func XCTAssertUnsortedEqual<T>(
Can you move this to `TestUtilities.swift`? Could be useful elsewhere, and we already have some XCTAssert* utils there.

2023-10-11 10:09 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/Hooks/DocumentFilter.swift
> +        operations: [String] = [],
The semantics, which probably need better documenting, if you didn't catch them are as follows:

- If you do not specify a `filter` key in your config file, then `config.filter: DocumentFilter?` will be `nil` and no filtering will take place.
- If you _do_ specify a `filter` key in your config file, then filtering will take place.
- When filtering takes place, we start with empty paths and schemas and only include what you asked for.

Concretely this means that `schemas: []` and `schemas: nil` are equivalent, and mean you don't get any schemas, apart from those that may be required by other things you asked for (paths or operations).

The optionality at this level was for decoding from the YAML file, without having to duplicate a type that differs only in the optionality of each property.

2023-10-11 10:09 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/Hooks/DocumentFilter.swift
> +    public var paths: [OpenAPI.Path]?
Yes, an important one.

This allows you to only specify strings that can be used as keys in the `paths` object in the OpenAPI document. Specifically, it allows you to specify paths that take parameters, e.g. `/books/{id}`, but won't allow arbitrary strings.

2023-10-11 10:09 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/Hooks/DocumentFilter.swift
> +public struct DocumentFilter: Codable, Sendable {
While it's true that it's only used for config. It is also `Encodable` so we can use the same trick you used for the `generate` command help message. That is, we encode an example filter to YAML, when rendering the help message[^1].

[^1]: https://github.com/apple/swift-openapi-generator/pull/319/files#diff-32fe5d86e35489cd6f0071eb479054741c5fc75b3d88ec27fa73ed9bea7d359bR31 

2023-10-11 10:09 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/Hooks/DocumentFilter.swift
> +/// - Todo: Add endpoint support
Nope, thanks for catching; removed in f782f3a.

2023-10-11 11:25 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Hooks/DocumentFilter.swift
> +        operations: [String] = [],
Ah right, I forgot we do the union of all the various filtering types. Makes sense, thanks for the detailed explanation.

2023-10-11 11:27 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Hooks/FilteredDocument.swift
> +        case .any(of: let schemas, _):
Yeah for diffs it's nicer, but I don't expect this to change, as these are fundamental JSONSchema types. I've just been trained to avoid fallthrough if I can.

2023-10-11 11:29 UTC, czechboy0 commented on Sources/swift-openapi-generator/FilterCommand.swift
> +    }
Yes, it's fully internal to our needs, so no need to avoid improving it.

2023-10-13 09:05 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/Hooks/FilteredDocument.swift
> +        case .any(of: let schemas, _):
Done in 997e4dd.

2023-10-13 09:05 UTC, simonjbeaumont commented on Sources/swift-openapi-generator/FilterCommand.swift
> +    }
Done in 3833ef9.

2023-10-13 09:05 UTC, simonjbeaumont commented on Sources/swift-openapi-generator/FilterCommand.swift
> +struct _FilterCommand: AsyncParsableCommand {
Done in 9df55ed.

2023-10-13 09:21 UTC, czechboy0 reviewed
A few more comments, otherwise looks great.

2023-10-13 09:21 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Articles/Configuring-the-generator.md
> +The geneartor supports filtering the OpenAPI document prior to generation, which can be useful when
```suggestion
The generator supports filtering the OpenAPI document prior to generation, which can be useful when
```

2023-10-13 09:21 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Articles/Configuring-the-generator.md
> +generating client code for a subset of a large API.
```suggestion
generating client code for a subset of a large API, or splitting an implementation of a server across multiple modules.
```

2023-10-13 09:21 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Articles/Configuring-the-generator.md
> +For example, to generate client code for only the operations with a given tag, use the following config:
```suggestion
For example, to generate code for only the operations with a given tag, use the following config:
```

2023-10-13 09:21 UTC, czechboy0 commented on Sources/swift-openapi-generator/FilterCommand.swift
> +        try document.validate()
I think you actually want to use the function `validateDoc` from `validateDoc.swift`, which also takes the diagnostic collector and uses the same logic as the generation command. By default the `validate()` call contains a slightly different set of validations, and is overly strict about schema warnings.

2023-10-13 09:21 UTC, czechboy0 commented on Sources/swift-openapi-generator/FilterCommand.swift
> +            FileHandle.standardOutput.write(try YAMLEncoder().encode(document))
Should we generate JSON if the user gave us JSON here?

2023-10-13 09:29 UTC, simonjbeaumont commented on Sources/swift-openapi-generator/FilterCommand.swift
> +            FileHandle.standardOutput.write(try YAMLEncoder().encode(document))
I hadn't considered that, good point. Should we detect this or just base it on the input path extension for now?

2023-10-13 09:29 UTC, simonjbeaumont commented on Sources/swift-openapi-generator/FilterCommand.swift
> +        try document.validate()
We could remove this altogether, I suppose, but I'll update to the function that takes the `DiagnosticCollector`.

2023-10-13 09:29 UTC, simonjbeaumont commented on Sources/swift-openapi-generator/Documentation.docc/Articles/Configuring-the-generator.md
> +For example, to generate client code for only the operations with a given tag, use the following config:
I don't think this one is right, given the YAML below is explicitly for a concrete example that has `client`, similar to examples above in the doc.

2023-10-13 10:17 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Articles/Configuring-the-generator.md
> +For example, to generate client code for only the operations with a given tag, use the following config:
Sure, let's keep the "client" word here then.

2023-10-13 11:06 UTC, simonjbeaumont commented on Sources/swift-openapi-generator/FilterCommand.swift
> +        try document.validate()
I decided to remove the call to validate here instead.

I wrote the patch to make use of `validateDoc` but I needed to either remove the config parameter it accepts (and doesn't use) or provide a config from here (which relies on providing a generator mode). Neither of these seemed worth it.

I then realised that I don't want to do this for two reasons:
1. Folks might actually want to be using the filter to remove parts of a doc that has validation errors.
2. The implementation of validateDoc fully dereferences the doc and then loops over all components again, and I spent some time making sure the filter command was one-pass.

2023-10-13 12:06 UTC, czechboy0 approved these changes
:shipit:

2023-10-13 12:20 UTC, merged