Add specific errors to content types
apple/swift-openapi-generator pull request #471
Opened 2023-12-11 15:18 UTC by PARAIPAN9

### Motivation

- Fixes #342.

### Modifications

- Add a ContentTypeError enum that has specific error cases used when content types are parsed.

### Result

- This will affect the ContentType struct.

### Test Plan

- Test it on an openapi document to make sure the errors are thrown as intended.

2023-12-11 22:51 UTC, simonjbeaumont commented
@swift-server-bot test this please

2023-12-12 09:15 UTC, PARAIPAN9 commented
You're very welcome! Thank you for considering the changes, and I completely understand the priority of shipping 1.0.0 first. I'm thrilled to contribute, and eagerly looking forward to the exciting milestone of the first release.

2023-12-13 16:34 UTC, czechboy0 commented
Hi @PARAIPAN9 - the issue might not have been super clear, but the issue was about doing the work of walking the OpenAPI document, and validating all the content type strings that exist there, in the `validateDoc` function.

That way, we'd catch invalid content types at the start, instead of doing so later when we're trying to generate code.

The errors emitted today, when an invalid content type is encountered, are good enough, we just don't do the validation at the start, so it can lead to a more confusing debugging experience.

Does that make sense? If that task is not something you want to pick up, no worries at all, just let me know and I'd unassign you. 🙂

2023-12-13 16:34 UTC, czechboy0 requested changes
See comment above, the task is slightly different.

2023-12-13 18:54 UTC, PARAIPAN9 commented
Ah, thank you for the clarification. It's ok, I'll continue working on it.

2023-12-19 08:46 UTC, czechboy0 requested changes
Thanks - just a few more comments about how we can validate all the content types and emit more information if an invalid content type is found.

2023-12-19 08:46 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/validateDoc.swift
> +    let mediaTypePattern = "^[a-zA-Z]+/[a-zA-Z][a-zA-Z-]*$"
To avoid duplicating similar logic, you can validate whether the content type is valid by trying to create a `_OpenAPIGeneratorCore.ContentType` value from the string, and if it fails, it's an invalid content type. This regex doesn't fully represent the requirements, and we don't want to have to keep multiple pieces of similar logic in sync manually.

2023-12-19 08:46 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/validateDoc.swift
> +func extractContentTypes(from doc: ParsedOpenAPIRepresentation) -> [String] {
You could change this to a visitor pattern, where you provide a closure with the signature `(String) -> Bool`, that returns `true` if the content type is valid. And this method would be responsible for walking all the places that have content types.

That way, you can then emit a good diagnostic about _which_ content type was invalid, and _where_ it was found. That's important for debugging.

2023-12-19 08:46 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/validateDoc.swift
> +
We should also validate the content types in `#/components/requestBodies` and `#/components/responses` here.

2023-12-20 12:34 UTC, czechboy0 requested changes
Great, we're basically there - just added a few more suggestions, but this is the right shape!

2023-12-20 12:34 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/validateDoc.swift
> +                                    "Invalid content type string: '\(contentType.rawValue)' found in requestBody at path '\(path.rawValue)'. Must have 2 components separated by a slash '<type>/<subty
```suggestion
                                    "Invalid content type string: '\(contentType.rawValue)' found in requestBody at path '\(path.rawValue), method: \(endpoint.method.rawValue)'. Must have 2 components separated by a slash '<type>/<subtype>'.\n"
```

2023-12-20 12:34 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/validateDoc.swift
> +                                    "Invalid content type string: '\(contentType.rawValue)' found in responses at path '\(path.rawValue)'. Must have 2 components separated by a slash '<type>/<subtype
```suggestion
                                    "Invalid content type string: '\(contentType.rawValue)' found in responses at path '\(path.rawValue), method: \(endpoint.method.rawValue)'. Must have 2 components separated by a slash '<type>/<subtype>'.\n"
```

2023-12-20 12:34 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/validateDoc.swift
> +    for component in doc.components.requestBodies.values {
Let's iterate both keys and values, to allow us to print the key later down.
```suggestion
    for (key, component) in doc.components.requestBodies {
```

2023-12-20 12:34 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/validateDoc.swift
> +    for component in doc.components.responses.values {
```suggestion
    for (key, component) in doc.components.responses {
```

Same here. And please include the key in the diagnostic.

2023-12-20 12:34 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/validateDoc.swift
> +                        "Invalid content type string: '\(contentType.rawValue)' found in #/components/responses. Must have 2 components separated by a slash '<type>/<subtype>'.\n"
```suggestion
                    message:
                        "Invalid content type string."
                    context: ["contentType": contentType.rawValue, "location": "#/components/responses/\(key.rawValue)", "recoverySuggestion": "Must have 2 components separated by a slash '<type>/<subtype>'."]
```

Please keep the message a static string, so that we can group errors easily, and put the dynamic data into the context dictionary, for example like this. Please do this for the rest of the diagnostics you added.

2023-12-20 15:44 UTC, czechboy0 approved these changes
Great, thank you! Let's just get the CI green and I'll merge it.

2023-12-20 15:44 UTC, czechboy0 commented
@swift-server-bot test this please

2023-12-20 15:52 UTC, PARAIPAN9 commented
Perfect, You’re welcome!!

2023-12-20 16:05 UTC, merged