Validate references in validateDoc
apple/swift-openapi-generator pull request #500
Opened 2024-01-04 21:52 UTC by PARAIPAN9

### Motivation

- Fixes #341.
 
### Modifications

- Develop a function responsible for iterating through and validating the references within the OpenAPI document. If external references are present or if they are not found in the 'components' section, the function should throw errors.

### Result

- This will help catch invalid references before code generation.

### Test Plan

- Make sure that tests pass and wrote additional unit tests.

2024-01-04 21:53 UTC, PARAIPAN9 commented on Sources/_OpenAPIGeneratorCore/Parser/validateDoc.swift
> +    let filteredDoc = try FilteredDocumentBuilder(document: doc).filter()
The issue mentioned that the documentation should be filtered before validation. I'm not entirely sure if this is the intended approach.

2024-01-05 08:41 UTC, simonjbeaumont requested changes

2024-01-05 08:41 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/Parser/validateDoc.swift
> +    let filteredDoc = try FilteredDocumentBuilder(document: doc).filter()
This filter doesn't do the right thing as the filter hasn't been configured to include anything.

However, it isn't necessary to do it here anyway because this function, `validateDoc(_:config:)`, is called as a post-transition hook after parsing the OpenAPI document _after_ the existing post-transition hook for filtering the doc[^1].

[^1]: https://github.com/apple/swift-openapi-generator/blob/85fec92ea3/Sources/_OpenAPIGeneratorCore/GeneratorPipeline.swift#L120

2024-01-08 13:23 UTC, simonjbeaumont commented
@swift-server-bot test this please

2024-01-08 13:24 UTC, simonjbeaumont approved these changes

2024-01-08 13:25 UTC, simonjbeaumont commented
Thanks @PARAIPAN9!

2024-01-08 13:33 UTC, PARAIPAN9 commented
You're welcome, always a pleasure to contribute!!

2024-01-08 14:20 UTC, czechboy0 approved these changes

2024-01-08 14:21 UTC, merged