[Generator] Add support of deepObject style in query params
apple/swift-openapi-generator pull request #538
Opened 2024-03-07 13:22 UTC by kstefanou52

### Motivation

https://github.com/apple/swift-openapi-generator/issues/259

~Depends on https://github.com/apple/swift-openapi-runtime/pull/100 landing first and getting released, and the version dependency being bumped here.~

### Modifications

Added `deepObject` style to serializer & parser in order to support nested keys on query parameters.

### Result

Support nested keys on query parameters.

### Test Plan

Adapted snippet tests (SnippetBasedReferenceTests)

2024-03-07 15:50 UTC, simonjbeaumont commented
Thanks @kstefanou52 for taking the time to tackle this. We'll park this PR review until we land the runtime PR.

2024-04-16 09:56 UTC, czechboy0 commented
@kstefanou52 Ok please bump the runtime dependency to 1.4.0 in Package.swift and you should be able to finish the generator changes.

2024-04-16 13:45 UTC, kstefanou52 commented
@czechboy0 Done! I have created some tests, but I'm not sure if you would like to add more. Could you please suggest any additional tests you think might be necessary? Thank you!

2024-04-16 15:16 UTC, czechboy0 requested changes
One code change suggested, and regarding the extra tests - you're right 🙂 


Start by adding a similar parameter like you did in the snippet tests, but this time to `petstore.yaml`, which makes it available in generated form in `PetstoreConsumerTests`. There, please extend one client and one server unit test to verify that the serialization/deserialization is correctly piped through all the way. The relevant test classes are `Test_Client` and `Test_Server`.

2024-04-16 15:16 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Translator/Parameters/TypedParameter.swift
> -                    return nil
I think the `return nil` needs to stay, just should live in the `default` case now.

2024-04-17 10:33 UTC, kstefanou52 commented on Sources/_OpenAPIGeneratorCore/Translator/Parameters/TypedParameter.swift
> -                    return nil
That's correct, I must have deleted it by mistake.

2024-05-21 20:34 UTC, simonjbeaumont commented
Just checking in on this one. Is it ready for review again? (Thanks for the effort here!)

2024-05-25 11:34 UTC, kstefanou52 commented
Hi @simonjbeaumont! Unfortunately some tests are failing, I'll work on this on weekend and I'll let you know. Cheers!

2024-07-22 14:21 UTC, czechboy0 commented
Hi @kstefanou52 - do you expect to be able to come back to finish this? 🙂 It's also okay if you can't and someone else will pick up where you left off.

2024-09-04 09:00 UTC, kstefanou52 commented
@czechboy0 I'm apologising for my late response. I'll try to catch up and complete the PR by the end of the week.

2024-10-03 07:33 UTC, czechboy0 commented
Hi @kstefanou52 - let us know if you need any help with this? I think it just needs to be updated from the main branch and a conflict resolved, but otherwise might be good to go?

2024-10-26 13:04 UTC, kstefanou52 commented on Tests/PetstoreConsumerTests/Test_Server.swift
> +            XCTAssertEqual(input.query.sort, .init(id: "ascending", name: "descending"))
This test fails because input.query.sort is nil. It appears there’s an issue in the runtime library method [decodeRootIfPresent(_ type:) throws -> T](https://github.com/apple/swift-openapi-runtime/blob/daa2fb54fe4a7f5187d7286047d5144c8cb97477/Sources/OpenAPIRuntime/URICoder/Decoding/URIValueFromNodeDecoder.swift#L83).
The node being returned is [id: ascending, name: descending], and, as expected, there's no `node[rootKey]`, so `currentElementAsArray().isEmpty` returns true and the decoding fails.

I think we may need to update the runtime library with something like this:
```
func decodeRootIfPresent<T: Decodable>(_ type: T.Type = T.self) throws -> T? {
    // The root is only nil if the node is empty.
    if try currentElementAsArray().isEmpty { return nil }
    if style != .deepObject, try currentElementAsArray().isEmpty {
        return nil
    }
    return try decodeRoot(type)
}
```

2024-10-26 13:06 UTC, kstefanou52 commented
Hello @czechboy0 and @arthurcro, I've made some progress, but I'm facing an issue with one of the unit tests. The code appears to work as expected, but I suspect there may be a problem with the runtime library. I’d appreciate your thoughts on this; more details can be found [here](https://github.com/apple/swift-openapi-generator/pull/538/commits/adfa77efbe029a745ce7c26297bc9427bcda5e9d#r1817848222).

2024-10-26 15:27 UTC, czechboy0 commented
Can you elaborate? The link doesn't really say what the issue is - what are you seeing and what are you expecting?

2024-10-26 15:35 UTC, czechboy0 commented on Tests/OpenAPIGeneratorReferenceTests/SnippetBasedReferenceTests.swift
> +                    required: true
```suggestion
                    required: false
```

Let's use `required: false`, or if you'd like to test it being required, make one of the properties required.

2024-10-26 15:35 UTC, czechboy0 commented on Tests/PetstoreConsumerTests/Test_Server.swift
> +            XCTAssertEqual(input.query.sort, .init(id: "ascending", name: "descending"))
Yeah that's possible, can you open a PR to the runtime library with a test first so we agree on what the expected behavior should be? If you try that, does that make this test pass?

2024-10-26 15:37 UTC, kstefanou52 commented on Tests/PetstoreConsumerTests/Test_Server.swift
> +            XCTAssertEqual(input.query.sort, .init(id: "ascending", name: "descending"))
Yes it passed!

2024-10-26 16:04 UTC, czechboy0 commented on Tests/PetstoreConsumerTests/Test_Server.swift
> +            XCTAssertEqual(input.query.sort, .init(id: "ascending", name: "descending"))
Ok let's get that change into the runtime library then!

2024-10-29 06:52 UTC, czechboy0 commented on Tests/PetstoreConsumerTests/Test_Server.swift
> +            XCTAssertEqual(input.query.sort, .init(id: "ascending", name: "descending"))
@kstefanou52 Will you be able to open that PR to the runtime library?

2024-10-29 09:27 UTC, kstefanou52 commented
Hey @czechboy0, I just opened the [runtime PR](https://github.com/apple/swift-openapi-runtime/pull/125). Please let me know if there are any additional tests we should add. Thanks!

2024-10-29 09:28 UTC, kstefanou52 commented on Tests/PetstoreConsumerTests/Test_Server.swift
> +            XCTAssertEqual(input.query.sort, .init(id: "ascending", name: "descending"))
Done!

2024-11-25 15:01 UTC, czechboy0 requested changes
Sorry it took longer than expected, the deepObject improvements landed in runtime 1.7.0, so you should be able to bring this branch up to speed again. Added a few suggestions

2024-11-25 15:01 UTC, czechboy0 commented on Tests/OpenAPIGeneratorReferenceTests/SnippetBasedReferenceTests.swift
> +                          type: string
Please add one more parameter here, one that is required and has one of the object properties required as well. I want to see that the default parameter is working correctly below.

2025-02-11 08:54 UTC, kstefanou52 commented
Hello @czechboy0 , I hope you are doing well. I found some time yesterday to rebase my PR and add the unit tests you requested.

2025-02-11 10:37 UTC, czechboy0 approved these changes
Looks great, thank you!

2025-02-11 10:40 UTC, czechboy0 commented
@kstefanou52 Seems some of the changed tests are failing, and the formatter needs to be rerun (details: https://github.com/apple/swift-openapi-generator/blob/main/CONTRIBUTING.md#run-ci-checks-locally)

2025-02-11 15:56 UTC, czechboy0 commented
@kstefanou52 Still seems to be failing

2025-06-20 13:39 UTC, alishba-bloomandwild commented
Hi @czechboy0, just checking in to see if you're able to merge these changes yet or if the tests are still failing?

2025-06-20 14:10 UTC, czechboy0 commented
Hi @alishba-bloomandwild - there now seems to be a conflict. I'll let @kstefanou52 take a look when they have time, but this is close to landing.

2025-06-23 11:59 UTC, kstefanou52 commented
@czechboy0 Hey! I'll do a rebase and run the tests locally during the week. I'll let you know when it will be ready.

2025-06-24 10:17 UTC, alishba-bloomandwild commented
I appreciate you taking the time to look into this, as it's currently a blocker for us. @kstefanou52

2025-07-08 00:37 UTC, mheh commented
Excited about this one too.

2025-07-10 15:12 UTC, kstefanou52 commented
@czechboy0 @alishba-bloomandwild I plan to work on this during the weekend. I hope by Monday it will be ready. Thanks for your patience.

2025-07-14 16:08 UTC, kstefanou52 commented
@czechboy0 I ran the tests locally and I'm getting a lot of `trailing spaces` errors in the Soundness/YAML lint check, even on files I haven't touched. Is that normal? Should I fix them? Thanks!

2025-07-16 07:52 UTC, czechboy0 commented
The formatter in CI is happy, so it might be a local issue. I'll merge this once the rest of the CI passes - thanks! 🙏

2025-07-16 08:37 UTC, merged