Add the `frozen` keyword only to enums with the `public` or `package` modifiers
apple/swift-openapi-generator pull request #595
Opened 2024-07-21 03:24 UTC by ojun9

### Motivation
As reported in https://github.com/apple/swift-openapi-generator/issues/586, using Xcode 16 Beta 3, the generated Type.swift file now shows multiple warnings due to the `@frozen` attribute being applied to non-public enums. 

### Modifications
In order to resolve the above issue, I have modified the code to annotate the `@frozen` keyword only on `enum` with the `public` or `package` modifiers.

### Result
No warnings are issued when the `@frozen` keyword is annotated on enums with the `public` or `package` modifiers.

2024-07-21 13:04 UTC, czechboy0 requested changes

2024-07-21 13:04 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Renderer/TextBasedRenderer.swift
> +        func shouldAnnotateAsFrozen(_ enumDesc: EnumDescription) -> Bool {
Could you break this method out and add unit tests for it, and update the reference tests as well please?

2024-07-21 16:05 UTC, ojun9 commented on Sources/_OpenAPIGeneratorCore/Renderer/TextBasedRenderer.swift
> +        func shouldAnnotateAsFrozen(_ enumDesc: EnumDescription) -> Bool {
I've broken out the method into an extension and added unit tests for it. I've also updated the reference tests accordingly. Please review and let me know if any further changes are needed!

2024-07-21 17:44 UTC, czechboy0 approved these changes
Great, thank you!

2024-07-21 17:44 UTC, czechboy0 commented
@swift-server-bot test this please

2024-07-22 05:14 UTC, czechboy0 commented
@swift-server-bot test this please

2024-07-22 06:35 UTC, czechboy0 commented
For the 5.9 and 5.9.0 pipelines, we're running into the deprecation warning being escalated to an error. We already disabled warnings-as-errors on most other pipelines, please also comment out this line in the two files for 5.9 and 5.9.0, then the CI should pass.

https://github.com/apple/swift-openapi-generator/blob/285ebba6300019d5eabcde15173809d098ac14f4/docker/docker-compose.2204.59.yaml#L14

2024-07-22 11:33 UTC, czechboy0 commented
@swift-server-bot test this please

2024-07-22 11:48 UTC, czechboy0 approved these changes

2024-07-22 11:55 UTC, merged