Enforce error diagnostics by aborting execution
apple/swift-openapi-generator pull request #607
Opened 2024-08-02 14:37 UTC by PARAIPAN9

### Motivation

- Fixes https://github.com/apple/swift-openapi-generator/issues/180

### Modifications

- Create `DiagnosticSubmitter` wrapper class.

### Result

- The `DiagnosticSubmitter` throws an error when a diagnostic with severity `.error` is submitted.

### Test Plan

- Make sure all tests pass.

2024-08-02 16:14 UTC, PARAIPAN9 commented
I have a question because I'm a bit confused about what to do after the creation of the wrapper. Should we use the wrapper in place of the extensions from DiagnosticCollector?

2024-08-02 16:50 UTC, czechboy0 commented
I think `DiagnosticCollector`'s `emit` method should become throwing, and then create a new concrete collector implementation that looks something like this:

```swift
struct ErrorThrowingDiagnosticCollector: DiagnosticCollector {
    var upstream: any DiagnosticCollector

    func emit(_ diagnostic: Diagnostic) throws {
        upstream.emit(diagnostic)
        if diagnostic.severity == .error { throw diagnostic }
    }
}
```

And then use this collector by default, wrapping today's collector.

2024-08-02 21:10 UTC, PARAIPAN9 commented
> I think `DiagnosticCollector`'s `emit` method should become throwing, and then create a new concrete collector implementation that looks something like this:
> 
> ```swift
> struct ErrorThrowingDiagnosticCollector: DiagnosticCollector {
>     var upstream: any DiagnosticCollector
> 
>     func emit(_ diagnostic: Diagnostic) throws {
>         upstream.emit(diagnostic)
>         if diagnostic.severity == .error { throw diagnostic }
>     }
> }
> ```
> 
> And then use this collector by default, wrapping today's collector.

It makes sense, perfect!!

2024-08-05 07:24 UTC, czechboy0 commented on Sources/swift-openapi-generator/GenerateOptions+runGenerator.swift
> +            try ErrorThrowingDiagnosticCollector(upstream: diagnostics).emit(error)
We should only create `ErrorThrowingDiagnosticCollector` in one place, not in the translate methods (those will already get a `DiagnosticCollector` value, which will already have this collector).

Just update the block around line 45 to something like:

```swift
let innerDiagnostics: any DiagnosticCollector & Sendable
if let diagnosticsOutputPath {
    let _diagnostics = _YamlFileDiagnosticsCollector(url: diagnosticsOutputPath)
    finalizeDiagnostics = _diagnostics.finalize
    innerDiagnostics = _diagnostics
} else {
    innerDiagnostics = StdErrPrintingDiagnosticCollector()
    finalizeDiagnostics = {}
}
let diagnostics = ErrorThrowingDiagnosticCollector(upstream: innerDiagnostics)
```

And please remove all the other places where you're creating `ErrorThrowingDiagnosticCollector`. The only changes in the individual translate* files should be the adaptation to the `emit` method now throwing.

2024-08-05 07:25 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/GeneratorPipeline.swift
> +            try ErrorThrowingDiagnosticCollector(upstream: diagnostics).emit(diagnostic)
The `diagnostics: any DiagnosticCollector` (line 104) should already be a `ErrorThrowingDiagnosticCollector`, so this shouldn't be necessary (see my other comment at the bottom).

2024-08-05 07:25 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Diagnostics.swift
>      /// - Parameter diagnostic: The diagnostic to submit.
Yup these changes look great 🙏

2024-08-05 13:57 UTC, czechboy0 commented
@swift-server-bot test this please

2024-08-05 15:52 UTC, czechboy0 commented
Ok the code looks good, would you be able to add one test that constructs the pipeline with a malformed input and ends up throwing the error? Just to verify that it's really working?

2024-08-05 15:58 UTC, PARAIPAN9 commented
Sure.

2024-08-12 05:33 UTC, czechboy0 commented
@swift-server-bot test this please

2024-08-12 05:54 UTC, czechboy0 commented
Got some build failures on Linux:

```
/code/Tests/OpenAPIGeneratorTests/Test_GenerateOptions.swift:38:34: error: cannot call value of non-function type 'String'
        let arguments = [docPath.path(), "--config", configPath.path]
                                 ^   ~~
                                     
/code/Tests/OpenAPIGeneratorTests/Test_GenerateOptions.swift:42:94: error: 'nil' requires a contextual type
            try await generator.runGenerator(outputDirectory: outputDirectory, pluginSource: nil, isDryRun: false)
```

You can fix the first one by using `docPath.path` (the property) instead. For the second, just pass the "build plugin" plugin source case.

2024-08-12 09:16 UTC, czechboy0 commented
@swift-server-bot test this please

2024-08-12 09:35 UTC, czechboy0 commented
```
** Running /code/scripts/check-license-headers.sh...
** ERROR: Unsupported file extension for file (exclude or update this script): Tests/OpenAPIGeneratorTests/Resources/Docs/malformed-openapi.yaml
```

You'll need to add the file to the license check ignore list.

2024-08-12 09:42 UTC, czechboy0 commented
Hmm this actually breaks 5.9.0, because it creates a dependency of a test target on an executable target. https://ci.swiftserver.group/job/swift-openapi-generator-swift590-prb/246/console

To fix this, you'll need to start depending on `_OpenAPIGeneratorCore` instead of `swift-openapi-generator`, and move `_YamlFileDiagnosticsCollector` to `_OpenAPIGeneratorCore`, and create a method called e.g. `preparedDiagnosticsCollector(...) -> DiagnosticCollector & Sendable` that lives in `_OpenAPIGeneratorCore`. Then just test that method, and call the method from the `swift-openapi-generator` code. 

I don't think we'll be able to make the new dependency work otherwise.

2024-08-14 21:29 UTC, czechboy0 commented on Sources/swift-openapi-generator/GenerateOptions+runGenerator.swift
> +        let diagnostics = ErrorThrowingDiagnosticCollector(upstream: innerDiagnostics)
I was thinking you could move all this logic into the prepare... function, so that it can be called from tests and also from here.

The method would take an optional URL, depending on whether the user provided a diagnostic URL or not. But the whole diagnostics collector construction would happen in that method.

2024-08-15 08:57 UTC, PARAIPAN9 commented on Sources/swift-openapi-generator/GenerateOptions+runGenerator.swift
> +        let diagnostics = ErrorThrowingDiagnosticCollector(upstream: innerDiagnostics)
Aha, ok.

2024-08-19 07:01 UTC, czechboy0 commented
@swift-server-bot test this please

2024-08-19 07:10 UTC, czechboy0 commented on Package.swift
> +            dependencies: ["swift-openapi-generator"],
You also need to add an explicit dependency on ArgumentParser, the 5.9.0 CI pipeline is failing with:

```
/code/Tests/OpenAPIGeneratorTests/Test_GenerateOptions.swift:39: error: undefined reference to '$s14ArgumentParser17ParsableArgumentsPAAE5parseyxSaySSGSgKFZ'
```

2024-08-31 18:37 UTC, czechboy0 commented
@swift-server-bot test this please

2024-09-16 10:01 UTC, czechboy0 commented
@swift-server-bot test this please

2024-09-16 11:09 UTC, czechboy0 commented
@PARAIPAN9 The CI is happy, but I believe we still need to move the remaining diagnostic collection code into the new `prepare...` function, so that it's called from the CLI and also from tests. Right now we're still re-creating the collectors using different code in the CLI vs the tests.

2024-09-16 11:09 UTC, czechboy0 requested changes
See comment above.

2024-09-18 08:18 UTC, czechboy0 approved these changes
Thank you @PARAIPAN9, looks great now!

2024-09-18 08:22 UTC, merged