Proposal for error handling
apple/swift-openapi-generator pull request #626
Opened 2024-09-17 08:33 UTC by gayathrisairam

### Motivation

Swift OpenAPI runtime doesn't allow for fine grained error handling. This PR adds a proposal for improved error handling in Swift OpenAPI runtime.

### Modifications

- Add SOAR-011: Improved error handling.
 (See the [proposal](https://github.com/gayathrisairam/swift-openapi-generator/blob/error_handling/Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md) for details)

### Result

n/a

### Test Plan

n/a

2024-09-17 08:34 UTC, czechboy0 commented
Please also add a link to it in the Proposals.md file 🙂

2024-09-17 08:46 UTC, czechboy0 requested changes
Great work, thank you @gayathrisairam!

Added a few comments that are meant to help prepare the proposal for review (I'll hold off on commenting on the proposal itself for the review period).

Once you make these updates, we'll be able to send out the proposal for wider review.

2024-09-17 08:46 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md
> + When implementing a server with Swift OpenAPI Generator, users implement a type that conforms to a generated protocol, providing one method for each API operation defined in the OpenAPI document. At
```suggestion
 When implementing a server with Swift OpenAPI Generator, users implement a type that conforms to a generated protocol, providing one method for each API operation defined in the OpenAPI document. At runtime, if this function throws, it's up to the server transport to transform it into an HTTP response status code – for example, some transport use `500 Internal Error`.
```

2024-09-17 08:46 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md
> +        return (HTTPResponse(status: 404), nil)
This needs to be a case from the `Operations.getGreeting.Output`, so e.g. `.notFound(.init())` here? Or since this is `GreetingError.authorizationError`, maybe using `.unauthorized(.init())` is more illustrative?

2024-09-17 08:46 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md
> +HummingBird also has an [error handling mechanism](https://docs.hummingbird.codes/2.0/documentation/hummingbird/errorhandling/)
```suggestion
Hummingbird also has an [error handling mechanism](https://docs.hummingbird.codes/2.0/documentation/hummingbird/errorhandling/)
```

2024-09-17 08:46 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md
> +            HTTPResponse.Status.forbidden
Nit: for clarity, we can shorten this

```suggestion
            .badRequest
        case .authorizationError:
            .forbidden
```

2024-09-17 08:46 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md
> +try handler.registerHandlers(on: transport, middlewares: [ErrorHandlingMiddleware()])
Nit: you're using the name `ErrorMiddleware` earlier, and `ErrorHandlingMiddleware` here. While the name itself will be discussed as part of the review, it might make sense to make them consistent to avoid confusion of whether the names will or will not be the same.

2024-09-17 08:48 UTC, gayathrisairam commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md
> + When implementing a server with Swift OpenAPI Generator, users implement a type that conforms to a generated protocol, providing one method for each API operation defined in the OpenAPI document. At
Even if the server transport transforms it to an error other than 500, OpenAPI eventually wraps it with 500

2024-09-17 08:52 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md
> + When implementing a server with Swift OpenAPI Generator, users implement a type that conforms to a generated protocol, providing one method for each API operation defined in the OpenAPI document. At
Hmm, can you link to where in code that happens? I'm not sure I follow

2024-09-18 05:08 UTC, gayathrisairam commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md
> + When implementing a server with Swift OpenAPI Generator, users implement a type that conforms to a generated protocol, providing one method for each API operation defined in the OpenAPI document. At
https://github.com/apple/swift-openapi-runtime/blob/main/Sources/OpenAPIRuntime/Interface/UniversalServer.swift#L115

2024-09-18 05:56 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md
> + When implementing a server with Swift OpenAPI Generator, users implement a type that conforms to a generated protocol, providing one method for each API operation defined in the OpenAPI document. At
That's where we wrap errors, but I don't think we ever choose the HTTP response code 500 in swift-openapi-runtime, that's purely a decision of the transport I believe.

2024-09-18 07:49 UTC, gayathrisairam commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md
> + When implementing a server with Swift OpenAPI Generator, users implement a type that conforms to a generated protocol, providing one method for each API operation defined in the OpenAPI document. At
Oh yes, you are right. It's Vapor that transforms any error that doesn't confirm to AbortError to 500.

2024-09-18 07:50 UTC, gayathrisairam commented
> Please also add a link to it in the Proposals.md file 🙂

Link to what?

2024-09-18 07:51 UTC, czechboy0 commented
> > Please also add a link to it in the Proposals.md file 🙂
> 
> Link to what?

Here, a link to your proposal: https://github.com/apple/swift-openapi-generator/blob/7c36ba905f6c0c9631d86b50b2b58e241bcb1837/Sources/swift-openapi-generator/Documentation.docc/Proposals/Proposals.md?plain=1#L54

2024-09-19 08:46 UTC, czechboy0 commented
The proposal is now In Review, forums thread: https://forums.swift.org/t/proposal-soar-0011-improved-error-handling/74736

2024-09-19 08:47 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md
> +- Status: **Awaiting Review**
```suggestion
- Status: **In Review**
```

2024-10-10 15:06 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md
> +- Status: **In Review**
```suggestion
- Status: **Ready for Implementation**
```

2024-10-10 15:08 UTC, czechboy0 commented
This proposal is now **Ready for Implementation**, see details on the forums: https://forums.swift.org/t/proposal-soar-0011-improved-error-handling/74736/31

2024-11-22 07:03 UTC, czechboy0 approved these changes
Landing now, we'll update the status once we have a Runtime release with this feature included.

2024-11-22 07:03 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0011.md
> +- Status: **Ready for Implementation**
```suggestion
- Status: **Implemented**
```

2024-11-22 07:26 UTC, merged