[Proposal] SOAR-0011 Generate enums for server variables
apple/swift-openapi-generator pull request #629
Opened 2024-09-18 12:51 UTC by theoriginalbit

### Motivation

As requested by @czechboy0 in #618 I have created this proposal for community feedback.

### Modifications

Added the proposal.

Also fixed a typo in the document for the proposal process.

### Result

N/A

### Test Plan

N/A

2024-09-18 13:29 UTC, czechboy0 commented
Looks good overall, almost ready to go into review. Could you just slightly elaborate on the behavior with the feature flag enabled/disabled in the API stability section? Right now it sounds like it could be API breaking even for folks who don't opt-in, which isn't the case.

2024-09-18 22:54 UTC, theoriginalbit commented
> Whoops, SOAR-0011 is already taken, please use SOAR-0012 :) #626

Fixed :)

2024-09-18 23:04 UTC, theoriginalbit commented
> Looks good overall, almost ready to go into review. Could you just slightly elaborate on the behavior with the feature flag enabled/disabled in the API stability section? Right now it sounds like it could be API breaking even for folks who don't opt-in, which isn't the case.

Done :)

2024-09-19 08:01 UTC, czechboy0 requested changes
Two more nits, after that I'm happy to send this into review.

2024-09-19 08:01 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0012.md
> +    - runtime (optional)
```suggestion
```

You mention the possibility to clean this up in the runtime library later in the proposal, but since we can't do this in v1 (it'd be a breaking change), I think we can just remove it from here.

2024-09-19 08:47 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0012.md
> +- Status: **Awaiting Review**
```suggestion
- Status: **In Review**
```

2024-10-11 17:18 UTC, czechboy0 commented on Sources/swift-openapi-generator/Documentation.docc/Proposals/SOAR-0012.md
> +- Status: **Ready for Implementation**
```suggestion
- Status: **Status: Implemented (1.4.0)**
```

This will go out with the next minor.

2024-10-11 18:08 UTC, czechboy0 approved these changes

2024-10-11 18:30 UTC, merged