Bumps OpenAPIKit to version 3.0.0-alpha.7 fixing an issue with trailing slashes.
apple/swift-openapi-generator pull request #69
Opened 2023-06-15 14:51 UTC by miguel-arrf

### Motivation
As discussed in #51, there was an issue with paths containing trailing slashes. The problem was identified in the [OpenAPIKit](https://github.com/mattpolzin/OpenAPIKit) dependency. It was fixed in the PR https://github.com/mattpolzin/OpenAPIKit/pull/274.

### Modifications
This PR updates the OpenAPIKit dependency version from `3.0.0-alpha.6` to `3.0.0-alpha.7` ([available here](https://github.com/mattpolzin/OpenAPIKit/releases/tag/3.0.0-alpha.7)), which includes the mentioned PR.

### Result
If a path ends with a trailing slash, such as `foo/bar/`, the generated functions will now correctly call the path `foo/bar/` instead of (as previously) `foo/bar`.

### Test Plan
No steps were taken to test this PR, as it is just a version update.

### Resolves
- Resolves https://github.com/apple/swift-openapi-generator/issues/51

2023-06-15 15:28 UTC, simonjbeaumont commented
@swift-server-bot add to allowlist

2023-06-15 18:23 UTC, czechboy0 commented
You could just change one of the paths in the integration test to end with a slash instead of adding another path+operation. But it'd be good for our tests to include this case.

2023-06-15 19:20 UTC, simonjbeaumont requested changes
Thanks for the fix. Based on the discussion here and on the issue, I'll mark this as request changes, until we get the test changed.

2023-06-19 13:49 UTC, czechboy0 requested changes
Thanks @miguel-arrf for updating the tests, but I don't think we need a new operation for it, as those are pretty expensive to maintain (as you just saw when adding a new one), so we add new ones sparingly, only when we can't extend existing ones. An easier alternative is to modify the path of one of the existing operations, and update the corresponding test.

2023-06-19 13:57 UTC, miguel-arrf commented
@czechboy0 Ah, I see! Thank you, I'll update it accordingly :)!

2023-06-19 17:27 UTC, miguel-arrf commented
(I still have some more tests to change, because of the Server!)

2023-06-19 18:07 UTC, czechboy0 commented on Tests/PetstoreConsumerTests/Test_Client.swift
> +            XCTAssertEqual(request.path, "/probe/")
Great, thanks for updating the `PetstoreConsumerTests` target as well – this is the important bit that verifies that the trailing slash is actually passed to the transport, and not stripped between OpenAPIKit and the generated code.

2023-06-19 18:08 UTC, czechboy0 approved these changes
Looks great, thank you, @miguel-arrf! 🙏

2023-06-19 18:11 UTC, simonjbeaumont commented
@miguel-arrf Looks great!

Would you like to update the PR description given you've gone to the effort of sorting the testing out?

> ⚠️ No steps have been taken yet to test this PR. The existing tests should be updated to include paths with trailing slashes.

2023-06-19 18:34 UTC, simonjbeaumont approved these changes

2023-06-19 18:43 UTC, merged

2023-06-20 09:24 UTC, miguel-arrf commented
Thanks @simonjbeaumont ! ☺️