Add common configuration for swift-format
apple/swift-openapi-generator pull request #73
Opened 2023-06-18 18:57 UTC by denil-ct

### Motivation

Fixes this [issue](https://github.com/apple/swift-openapi-generator/issues/40)

### Modifications

- Removed the configuration defined in `SwiftFormat.swift`.
- Used the json configuration file in the project root to generate the configuration object.

### Result

A single configuration file for swift-format, which will be easier to handle.

2023-06-18 19:21 UTC, denil-ct commented on Sources/_OpenAPIGeneratorCore/Extensions/SwiftFormat.swift
> +            .appending("/.swift-format")
I feel like this is quite susceptible to be triggered by other folders that have a `Sources` in their name. I started with it because it seemed the simplest. What is your opinion, am I being overly cautions here?

Maybe something like this might work better as it narrows down the search criteria?
```suggestion
        let configurationFilePath = #file
            .components(separatedBy: "swift-openapi-generator/Sources")[0]
            .appending("swift-openapi-generator/.swift-format")
```

Or is there some other way of getting the file location, that I am missing?

2023-06-18 21:49 UTC, czechboy0 commented
Hi @denil-ct, thanks for picking this one up!

While the approach of finding the format file on disk would work when the source package is cloned in some local directory, but we also have to consider the use case where the CLI is built as a binary, transferred to another machine, and executed there. In that scenario, we still need to support formatting as part of the code generation pipeline.

What might be worth investigating is how we could capture the format file at _compile_ time and embed it in the binary, so that it's then always available, even when not distributed as a source package.

There's some precedent in embedding an Info.plist for a CLI into the binary, so maybe that's a place to start looking. Possibly having an internal build tool plugin that reads the file and generates a variable that contains the string representation is another. I'll let you investigate these and propose which one you think will work best.

2023-06-18 21:51 UTC, czechboy0 requested changes
Marking as needs work as this doesn't cover the use case where the CLI is invoked outside of the generator source package.

2023-06-18 22:10 UTC, simonjbeaumont commented
Thanks @denil-ct for jumping in again!

> What might be worth investigating is how we could capture the format file at _compile_ time and embed it in the binary, so that it's then always available, even when not distributed as a source package.
> 
> There's some precedent in embedding an Info.plist for a CLI into the binary, so maybe that's a place to start looking. Possibly having an internal build tool plugin that reads the file and generates a variable that contains the string representation is another. I'll let you investigate these and propose which one you think works best.

Can't we use Swift PM for this. IIRC you can provide a `resources:` parameter in the target definition? Something like this:

```swift
...
    targets: [
...
        .executableTarget(
            name: "swift-openapi-generator",
            dependencies: [ ... ],
            resources: [
                .process(".swift-format"),
            ],
        ),
...
    ]
```

2023-06-18 22:22 UTC, czechboy0 commented
@simonjbeaumont IIRC, that'll create a resource bundle next to the binary, and if you transfer the binary to another machine without explicitly also transferring the resource bundle, it won't find it at runtime. But might require a confirmation in case I misremembered how it works.

So it'd work for a framework or an app target (it'd get embedded in that bundle), but not for an executable binary CLI that can be distributed on its own, as it doesn't get distributed as a bundle.

2023-06-19 10:41 UTC, czechboy0 commented
While trying @simonjbeaumont's suggestion, I stumbled upon a new SwiftPM 5.9 feature that allows embedding files in code: https://github.com/apple/swift-openapi-generator/issues/40#issuecomment-1596942582

2023-06-19 10:43 UTC, denil-ct commented
Shall I close this PR, then? @czechboy0

2023-06-19 10:46 UTC, denil-ct commented
Closing this PR for now, as we are blocked on [this](https://github.com/apple/swift-openapi-generator/issues/40#issuecomment-1596942582).

2023-06-19 10:46 UTC, closed without merging