Emit yaml processing errors that Xcode can display (#65)
apple/swift-openapi-generator pull request #81
Opened 2023-06-20 05:09 UTC by macblazer

### Motivation

If there are any errors in the openapi.yaml file currently the errors show up in the build transcript but are not shown in the Xcode issue sidebar and are also not linked to the openapi.yaml file in the sidebar. This makes it hard to know what has failed, and what to do to fix the file.

### Modifications

The YAML parser now catches decoding errors, and if they are common parsing or scanning errors it will emit a diagnostic message then throw a failure exit code.  This required importing the swift-argument-parser module into the main _OpenAPIGeneratorCore.

Added `absoluteFilePath` and `lineNumber` optional properties to the `Diagnostics` struct to capture more info. Modified the `Diagnostics.description` method to build a properly formatted message that Xcode can parse to point out the file and line causing issues.

### Result

In consuming projects, invalid yaml in the openapi.yaml file is now highlighted in the Xcode Issue Navigator after a build with this plugin.

### Test Plan

Added unit tests to verify emitted diagnostic and thrown error.  Also tested manually with an example project.

### Resolves

- Resolves #65.

2023-06-20 05:16 UTC, macblazer commented
I'm not particularly happy with adding `ArgumentParser` as a dependency into the `_OpenAPIGeneratorCore`.

Without it, any thrown error is caught by `ArgumentParser` and the thrown error's localizedDescription is used with a prefix of "Error: " which completely blows away any other diagnostic that I was able to emit.

The code now throws an `ArgumentParser.ExitCode.failure` after emitting a diagnostic with the proper information for Xcode to pick up the filepath and line number.  Using `ArgumentParser.ExitCode` was the only way I found to have the correct diagnostic message.

2023-06-20 05:24 UTC, Kyle-Ye commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +    private func throw_parsing_error(
Nit
```suggestion
    private func throwParsingError(
```

2023-06-20 05:30 UTC, czechboy0 requested changes
This is great, thanks for working on it, @macblazer! I think we can do this without the swift-argument-parser dependency, so I added a few comments.

2023-06-20 05:30 UTC, czechboy0 commented on Package.swift
> +                "_OpenAPIGeneratorCore"
It'd be great to avoid making the library depend on swift-argument-parser, see comments below how we should be able to remove it again.

2023-06-20 05:30 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Diagnostics.swift
> +    public var lineNumber: Int?
Since we'll either always have location, or not have location, let's represent it as 

```swift 
struct Diagnostic {
  //...
  struct Location {
    var filePath: String
    var lineNumber: Int
  }
  var location: Location?
}
```

2023-06-20 05:30 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Diagnostics.swift
> +                prefix = "\(filePath.path):"
Just use this codepath that works on all platforms, no need to branch out to the new API on newer OS versions.

2023-06-20 05:30 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +    private func possibly_throw_parsing_error(
```suggestion
    private func checkParsingError(
```

A naming suggestion - let's use camelCase, and suggested slightly different phrase.

2023-06-20 05:30 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +            var problem = Diagnostic.error(message: openAPIError.localizedDescription)
Can you add `location: Location? = nil` to the convenience initializer so that we can create the Diagnostic in one step here, instead of modifying it after creation?

2023-06-20 05:30 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +            throw ExitCode.failure
The Diagnostic itself conforms to error, so you can emit it into the DiagnosticCollector, and then also throw it. This will allow us to drop the dependency on swift-argument-parser.

2023-06-20 05:30 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +    private func throw_parsing_error(
```suggestion
    private func throwParsingError(
```

CamelCase, and please add a documentation comment for this method.

2023-06-20 05:30 UTC, czechboy0 commented on Tests/OpenAPIGeneratorCoreTests/Parser/Test_YamsParser.swift
> +            if let exitError = error as? ExitCode {
Here, you'd check for the Diagnostic being thrown, after you remove the swift-argument-parser dependency.

2023-06-20 13:01 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +            throw ExitCode.failure
When throwing the Diagnostic after emitting it, Xcode shows duplicate errors because ArgumentParser adds the thrown error (as a string) with `Error: ` in front of the description like so:

> /Users/<redacted>/GreetingServiceClient/Sources/openapi.yaml: error: Expected to find `info` key in the root Document object but it is missing.
> Error: /Users/<redacted>/GreetingServiceClient/Sources/openapi.yaml: error: Expected to find `info` key in the root Document object but it is missing.

Duplicate errors are maybe acceptable, but it's a tradeoff with adding the ArgumentParser dependency.

If the call to `emit()` is removed, then Xcode only gets the message with `Error: ` in front of it which does not link to the file and line number.  If the throw is removed then it crashes because of course it is an error and something should be thrown.

I don't see any way short of using `ExitCode.failure` to have ArgumentParser _not_ add `Error: ` to the front of a thrown instance's localizedDescription.  Maybe this should be a feature request on the ArgumentParser repo.

2023-06-20 13:03 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +            throw ExitCode.failure
I think it's probably fine to have the duplicate error in the log then, and let's file a separate issue to investigate if we can remove the duplication. It's more important that we don't introduce this dependency.

2023-06-21 04:28 UTC, macblazer commented on Tests/OpenAPIGeneratorCoreTests/Parser/Test_YamsParser.swift
> +            if let exitError = error as? ExitCode {
Done.

2023-06-21 04:29 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +    private func throw_parsing_error(
This method was completely removed in favor of throwing the Diagnostic directly.

2023-06-21 04:29 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +    private func possibly_throw_parsing_error(
Done

2023-06-21 04:30 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Diagnostics.swift
> +                prefix = "\(filePath.path):"
Done

2023-06-21 04:30 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Diagnostics.swift
> +    public var lineNumber: Int?
The lineNumber is still optional for some error cases, so I left that as optional inside the `Location` struct.

2023-06-21 04:30 UTC, macblazer commented on Package.swift
> +                "_OpenAPIGeneratorCore"
Done.

2023-06-21 04:31 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +    private func throw_parsing_error(
Done

2023-06-21 04:31 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +            var problem = Diagnostic.error(message: openAPIError.localizedDescription)
Done

2023-06-21 04:33 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +            throw ExitCode.failure
I found an alternate way to handle this de-duplication in the GenerateOptions+runGenerator.swift file (which is part of the executable target that already imports ArgumentParser) to catch **any** thrown `Diagnostic`, emit the nice error message from the diagnostic, then throw `ExitCode.failure` so ArgumentParser can terminate cleanly without any other messages.

The parser no longer calls `emit()` but simply throws the `Diagnostic`.

2023-06-21 04:51 UTC, czechboy0 requested changes
Looks great! Just added a few requests for missing documentation comments, otherwise it's almost ready to go.

2023-06-21 04:51 UTC, czechboy0 commented on Sources/swift-openapi-generator/GenerateOptions+runGenerator.swift
> +        }
Oh cool, does this avoid the duplication?

2023-06-21 04:51 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +    static func openAPIVersionError(versionString: String, location: Location) -> Diagnostic {
Please also document parameters

2023-06-21 04:51 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +    static func openAPIMissingVersionError(location: Location) -> Diagnostic {
Please also document parameters

2023-06-21 04:51 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +    private func checkParsingError(
Please also document parameters

2023-06-21 04:51 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Diagnostics.swift
>      public static func unsupported(
Please add documentation for the location parameter

2023-06-21 04:51 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Diagnostics.swift
>      /// - Returns: An error diagnostic.
Please add documentation for the location parameter

2023-06-21 04:51 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Diagnostics.swift
>      public static func warning(
Please add documentation for the location parameter

2023-06-21 04:51 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Diagnostics.swift
> +    public var location: Location?
Please add documentation for the properties inside Location, and the location property itself.

2023-06-22 04:32 UTC, macblazer commented on Sources/swift-openapi-generator/GenerateOptions+runGenerator.swift
> +        }
Yes, this fixes the duplication.  Any time the code throws a `Diagnostic` it will be emitted here, and ArgumentParser will exit with a failure code but no other output which is exactly what we want.

2023-06-22 05:23 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +    static func openAPIVersionError(versionString: String, location: Location) -> Diagnostic {
Done

2023-06-22 05:23 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +    static func openAPIMissingVersionError(location: Location) -> Diagnostic {
Done

2023-06-22 05:23 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Parser/YamsParser.swift
> +    private func checkParsingError(
Done

2023-06-22 05:24 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Diagnostics.swift
>      public static func unsupported(
Done

2023-06-22 05:24 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Diagnostics.swift
>      /// - Returns: An error diagnostic.
Done

2023-06-22 05:24 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Diagnostics.swift
>      public static func warning(
Done

2023-06-22 05:25 UTC, macblazer commented on Sources/_OpenAPIGeneratorCore/Diagnostics.swift
> +    public var location: Location?
Done

2023-06-22 05:32 UTC, czechboy0 approved these changes
Looks great, thanks!

2023-06-22 08:30 UTC, czechboy0 commented
@swift-server-bot add to allowlist

2023-06-22 10:43 UTC, simonjbeaumont approved these changes
Thanks @macblazer. This is a great step forward, here ❤️

2023-06-22 10:43 UTC, merged