Emit a descriptive error when running the generator on iOS, tvOS, or watchOS
apple/swift-openapi-generator pull request #87
Opened 2023-06-21 19:42 UTC by czechboy0

### Motivation

Resolves #86, which some adopters are hitting by accident.

### Modifications

Makes the generator itself build successfully on iOS, tvOS, watchOS, but not really, as I just added an explicit, clear error on those platforms pointing out that the adopter probably did this by accident, and how to fix it.

### Result

A clear, descriptive error is now emitted when the adopter links the `_OpenAPIGeneratorCore` target from e.g. an iOS app (most likely by accident):

```
.../swift-openapi-generator/Sources/_OpenAPIGeneratorCore/PlatformChecks.swift:4:8 Running the generator tool itself is not supported on iOS, tvOS, and watchOS. Check that your app is not linking the generator directly. For details, check out: https://github.com/apple/swift-openapi-generator/issues/86
```

### Test Plan

Tested locally by creating an iOS app with a lower deployment target and linked the generator directly. The error goes away when the linkages is removed, as expected.

2023-06-21 19:43 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/PlatformChecks.swift
> +#error("Running the generator tool itself is not supported on iOS, tvOS, and watchOS. Check that your app is not linking the generator directly. For details, check out: https://github.com/apple/swift
Feedback on the wording is welcome.

2023-06-21 20:48 UTC, denil-ct commented on Sources/_OpenAPIGeneratorCore/PlatformChecks.swift
> +#error("Running the generator tool itself is not supported on iOS, tvOS, and watchOS. Check that your app is not linking the generator directly. For details, check out: https://github.com/apple/swift
_The generator tool cannot run on iOS, tvOS, or watchOS. Make sure your app does not link against the generator directly. See https://github.com/apple/swift-openapi-generator/issues/86 for details._

I feel like this removes redundant words from the first sentence and on the second, it adds a more polite and imperative tone.

2023-06-22 10:11 UTC, simonjbeaumont requested changes
If we removed `_OpenAPIGeneratorCore` from the `products` then I think this is less likely to trip folks up. When I tested that approach locally, it is no longer offered by Xcode when adding the package dependency.

2023-06-22 10:11 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/PlatformChecks.swift
> +#if os(iOS) || os(tvOS) || os(watchOS)
I think this is what we want. Especially with upcoming `visionOS`.

```suggestion
#if !os(macOS) || !os(Linux)
```

2023-06-22 10:11 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/PlatformChecks.swift
> +// Details: https://github.com/apple/swift-openapi-generator/issues/86
I'd rather us carry informative comments _here_ than link out to Github.

```suggestion
// Emit a compiler error if this library is linked with a target in an adopter project.
```

2023-06-22 10:11 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/PlatformChecks.swift
> +#error("Running the generator tool itself is not supported on iOS, tvOS, and watchOS. Check that your app is not linking the generator directly. For details, check out: https://github.com/apple/swift
```suggestion
#error("_OpenAPIGeneratorCore is only to be used by swift-openapi-generator itself—your target should not link this library directly.")
```

2023-06-22 10:11 UTC, simonjbeaumont commented on Package.swift
> +        .iOS(.v13), .tvOS(.v13), .watchOS(.v6),
I'm really not a fan of us having to do this and would rather us consider removing `_OpenAPIGeneratorCore` from `products`.

If we do have to do it, we can make use of string version numbers for unreasonably high version numbers, e.g.

```suggestion
        .macOS(.v10_15),

        // The platforms below are not currently supported for running the generator itself.
        // We include them here to allow the us to emit a more descriptive compiler error.
        .iOS("99"), .tvOS("99"), .watchOS("99"),
```

2023-06-22 11:11 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/PlatformChecks.swift
> +#error("Running the generator tool itself is not supported on iOS, tvOS, and watchOS. Check that your app is not linking the generator directly. For details, check out: https://github.com/apple/swift
They might have linked the CLI though, not the Core library, so it might be confusing why we're warning about the library.

2023-06-22 11:11 UTC, czechboy0 commented on Package.swift
> +        .iOS(.v13), .tvOS(.v13), .watchOS(.v6),
I'll do the high version numbers, are 9999 instead also good? I've seen that used elsewhere.

2023-06-22 11:20 UTC, simonjbeaumont commented on Package.swift
> +        .iOS(.v13), .tvOS(.v13), .watchOS(.v6),
While they work in `@available` annotations, I tried them in this setting and it caused less readable errors because there are some other macro expansions which seem to rely on the major component being 2 digits. You can try and see for yourself what happens if you use 9999.

2023-06-22 11:21 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/PlatformChecks.swift
> +#error("Running the generator tool itself is not supported on iOS, tvOS, and watchOS. Check that your app is not linking the generator directly. For details, check out: https://github.com/apple/swift
OK, well we can append a little to the message?

```suggestion
#error("_OpenAPIGeneratorCore is only to be used by swift-openapi-generator itself—your target should not link this library or the plugin directly.")
```

2023-06-22 14:16 UTC, merged