Add missed keywords and character encoding
apple/swift-openapi-generator pull request #88
Opened 2023-06-21 20:35 UTC by denil-ct

### Motivation

Resolves https://github.com/apple/swift-openapi-generator/issues/34

The initial plan was to just resolve #34 , but then on checking noticed these could also improve.

### Modifications

- Added `Protocol` to the keywords set.
- Added `await` to the keywords set.
- Added a hexadecimal encoding for un-supported characters rather than having just an underscore for everything.
- Removed redundant keywords.

### Result

- Would be able to support `Protocol` and `await` as property names
- Encoding would help distinguish types properly. For eg. both `a b` and `a_b` would be rendered as `a_b`. This change would make it render `a_20b` and `a_b` respectively.
- This also helps us reduce the reserved keywords set by removing symbols and any keywords that prepend such symbols.

### Test Plan

Tested and verified for most of the combinations of special characters in-between alphanumeric characters.

2023-06-21 20:54 UTC, czechboy0 requested changes
Hi @denil-ct, thanks for another contribution!

Adding the two keywords is the quick fix and covers the original issues, so let's keep this PR to just that change, and please add to the unit tests to have some automation testing.

Could you break out the hex encoding experiment into a separate PR? I'd like us to discuss it more, but I don't want to block fixing #34 for it. Thanks! 🙏

2023-06-21 21:00 UTC, denil-ct commented
Sure, that makes sense. 
Quick question @czechboy0 , the initial issue mentions only the `Protocol` keyword. Should there be a new issue for `await` or can it be added on to that?

2023-06-21 21:03 UTC, czechboy0 commented
You can add await as well in this PR, the change is well understood. 

The hex stuff is new and we'll want to think about the implications to existing code etc, thus the separate PR.

2023-06-22 08:29 UTC, czechboy0 commented
@swift-server-bot add to allowlist

2023-06-22 08:30 UTC, czechboy0 approved these changes
Looks good, thanks! I checked the unit tests and we already cover the "keyword" case, so no real need to list all the keywords there.

2023-06-22 10:32 UTC, simonjbeaumont requested changes
@denil-ct thank you for once again for diving in 💪 

I left a comment about `Protocol`—not sure if we need it.

Additionally, would you mind adopting a PR title that would make a good entry in the release notes. For this PR, something like:

```
Add `await` to the identifiers escaping rules 
```

2023-06-22 10:32 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/Extensions/String.swift
> +        "Protocol",
Do we need this one? This works fine:

```swift
let Protocol = 1
print(Protocol)  // prints 1
```

2023-06-22 10:32 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/Extensions/String.swift
> +        "await",
This one is fun... TIL this fails only at use, but not on the variable declaration:

```swift
let await = 1  // this is fine
print(await)  // this is the problem
```

2023-06-22 10:40 UTC, denil-ct commented on Sources/_OpenAPIGeneratorCore/Extensions/String.swift
> +        "Protocol",
Unfortunately, we have a `Self` before it, which makes it a valid keyword in that context. If there is no self, then its not needed.

```swift
public init(
                Protocol: Swift.String? = nil,
                message: OpenAPIRuntime.OpenAPIValueContainer
            ) {
                self.Protocol = Protocol
                self.message = message
}
```

2023-06-22 10:47 UTC, denil-ct commented on Sources/_OpenAPIGeneratorCore/Extensions/String.swift
> +        "await",
So, this one is even more quirky. In the generated type init since await would be the RHS without any expression after it, I guess swift-format tries to apply a rule to move the next line over.

What we think will happen
```swift
public init(await: Swift.String? = nil, message: OpenAPIRuntime.OpenAPIValueContainer)
{
                self.await = await
                self.message = message
}
```

But what actually happens is
```swift
public init(await: Swift.String? = nil, message: OpenAPIRuntime.OpenAPIValueContainer) {
                self.await = await self.message = message
            }
```

2023-06-22 11:14 UTC, czechboy0 commented on Sources/_OpenAPIGeneratorCore/Extensions/String.swift
> +        "Protocol",
Yeah, `Protocol` came from a real OpenAPI doc, and it broke the build, so I think we need to add it as a reserved keyword, just like `Self` and `Type`.

2023-06-22 11:23 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/Extensions/String.swift
> +        "Protocol",
All makes perfect sense, thanks for clarifying.

2023-06-22 11:23 UTC, simonjbeaumont approved these changes

2023-06-22 11:40 UTC, merged