Generate deprecation annotations based on OpenAPI document
apple/swift-openapi-generator pull request #92
Opened 2023-06-26 21:20 UTC by simonjbeaumont

### Motivation

The OpenAPI spec supports declaring various parts of the API as deprecated, including operations, parameters, schemas, and properties. These can be surfaced in the generated code by adding `@available(*, deprecated)` annotations to the functions, types, and properties. 

### Modifications

- Support for deprecated OpenAPI schemas.
- Support for deprecated OpenAPI properties.
- Support for deprecated OpenAPI operations.

For deprecated operations, these are annotated on the function requirements in the generated `APIProtocol`.

### Result

Deprecated annotations are generated for the parts of the API marked as deprecated in the OpenAPI document.

### Test Plan

- Added `#/components/schemas/DeprecatedObject` to reference test.
- Added `#/components/schemas/ObjectWithDeprecatedProperty` to reference test.
- Marked `#/paths//probe//post` operation as deprecated in reference test.
- Marked `#/components/parameters/My-Request-UUID` parameter as deprecated in reference test.
- Unit tests for rendering `DeprecatedDescription` already existed.

### Resolves

Resolves #26.

2023-06-26 21:29 UTC, simonjbeaumont commented
Heh... I hadn't considered that our CI is building with warning-as-error and that this now generates a warning because there's deprecated symbols:

```
/code/Tests/PetstoreConsumerTests/TestClient.swift:44:29: error: 'probe' is deprecated
        _ input: Operations.probe.Input
                            ^
/code/Tests/PetstoreConsumerTests/TestClient.swift:45:34: error: 'probe' is deprecated
    ) async throws -> Operations.probe.Output {
                                 ^
[215/342] Compiling PetstoreConsumerTests Test_Client.swift
error: fatalError
1
Build step 'Execute shell' marked build as failure
```

Will update the flags in the CI build.

2023-06-27 05:05 UTC, czechboy0 requested changes
Looks great, thanks! Just added a few nits.

2023-06-27 05:05 UTC, czechboy0 commented on Tests/OpenAPIGeneratorReferenceTests/Resources/Docs/petstore.yaml
> +      additionalProperties: false
Did you explicitly turn off additional properties on purpose? You could just omit this field, and get the default behavior of an even smaller struct.

2023-06-27 06:27 UTC, simonjbeaumont commented on Tests/OpenAPIGeneratorReferenceTests/Resources/Docs/petstore.yaml
> +      additionalProperties: false
While that should probably be the case, it doesn't work like that today. Removing `additionalProperties: false` does not generate an empty struct, but instead generates:

```swift
public typealias DeprecatedObject = OpenAPIRuntime.OpenAPIObjectContainer
```

2023-06-27 06:31 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/Translator/CommonTranslations/translateStructBlueprint.swift
>              return structDecl
Good catch. This is the only place where we conditionally use `.commentable` which is unnecessary because it takes an optional so we should just pass through the comment from the blueprint, which itself is optional.

Updated (and simplified) in fixup commit d1444f4.

2023-06-27 06:32 UTC, simonjbeaumont commented on Sources/_OpenAPIGeneratorCore/Translator/CommonTypes/StructBlueprint.swift
> +    /// Whether the type should be annotated as deprecated.
Addressed in 4fc612f.

2023-06-27 06:35 UTC, czechboy0 commented on Tests/OpenAPIGeneratorReferenceTests/Resources/Docs/petstore.yaml
> +      additionalProperties: false
Ah right, yeah forgot about that. Lgtm

2023-06-27 06:35 UTC, czechboy0 approved these changes

2023-06-27 21:14 UTC, czechboy0 approved these changes
Looks great!

2023-06-27 21:18 UTC, merged

2023-06-28 05:37 UTC, michalsrutek commented on docker/docker-compose.2204.58.yaml
> +      # We'll desable -warnings-as-errors for now and revisit this when we
typo in `desable` - should be `disable`

2023-06-28 05:38 UTC, michalsrutek commented on docker/docker-compose.2204.58.yaml
> +      # We'll desable -warnings-as-errors for now and revisit this when we
in all 3 docker yaml files

2023-06-28 09:48 UTC, simonjbeaumont commented on docker/docker-compose.2204.58.yaml
> +      # We'll desable -warnings-as-errors for now and revisit this when we
🧹 Thanks for your keen eyes! 😁 Addressed in #93